### ISSUE TITLE
Highlight widget from different file

### ISSUE THREAD

**Issue by bobykurniawan11** [SimformSolutionsPvtLtd/flutter_showcaseview#102]
I'm trying to `highlight` a widget from different file on one flow.

```
     ShowCaseWidget.of(_scaffoldKey.currentContext).startShowCase([
        home_key,
        signal_key,
        chat_key,
        education_key,
        eof_key,
        home_header_key
      ]);
```
`home_header_key` from different file. Is it possible ?

**Comment by Ibrahimkamal** [comment]
any updates?

**Comment by vatsaltanna** [comment]
What do you mean by `different file`? Is it a different `route/screen`?

**Comment by vatsaltanna** [comment]
Closing this for now because of inactivity. Feel free to reopen for any other assistance.
