### ISSUE TITLE
Provide padding/margin for the widget overlay

### ISSUE THREAD

**Issue by yoseptara** [SimformSolutionsPvtLtd/flutter_showcaseview#103]
Is there any method to give space between the widget and the overlay? If no, could you please provide it?

Like in this picture (see the red line)

![Untitled](https://user-images.githubusercontent.com/49258329/116958314-c1395d00-accc-11eb-8a87-ba91c3bea980.png)

**Comment by SardorbekR** [comment]
@yoseptara have you found a solution?
