### ISSUE TITLE
showcase not showing text in one line even if it is not so big

### ISSUE THREAD

**Issue by muhammadjonyorqinov** [SimformSolutionsPvtLtd/flutter_showcaseview#105]

**Comment by vatsaltanna** [comment]
Could you please share more information on this ?

**Comment by muhammadjonyorqinov** [comment]
I have attached the example what I mean I used simple showcase without
withWidget

**Comment by vatsaltanna** [comment]
I can not find any attachment, could you please recheck?

**Comment by muhammadjonyorqinov** [comment]
![image](https://user-images.githubusercontent.com/33806774/120588591-e1397900-c450-11eb-8638-9afe6e8e8f9a.png)

**Comment by muhammadjonyorqinov** [comment]
Sorry about that, here it is.

**Comment by vatsaltanna** [comment]
Let me investigate and I will update here soon.
