### ISSUE TITLE
Support for Flutter 2.12.0-133.2.beta

### ISSUE THREAD

**Issue by OziTFA** [SimformSolutionsPvtLtd/flutter_showcaseview#106]

**Comment by vatsaltanna-simformsolutions** [comment]
Latest version of showcase view supports new versions of flutter

**Comment by BirjuVachhani** [comment]
@OziTFA I'd like to know more about your request here. What are you proposing or reporting specifically?

**Comment by OziTFA** [comment]
Thank you. solved new  version
