### ISSUE TITLE
Unhandled Exception: Exception: Please provide ShowCaseView context

### ISSUE THREAD

**Issue by maxwellmandela** [SimformSolutionsPvtLtd/flutter_showcaseview#107]
**Description**
I keep getting the error: Unhandled Exception: Exception: Please provide ShowCaseView context

**My widget initstate() **
`
@override
  void initState() {
    super.initState();

    WidgetsBinding.instance.addPostFrameCallback((_) =>
        ShowCaseWidget.startShowCase([KEY, KEY2]);
    });
  }
`

** And the widget build()**
`
return ShowCaseWidget(
      builder: Builder(
        builder: (context) => Scaffold(.....)))
`

**The showcace widget in AppBar actions**
`
Showcase(
                key: KEY,
                description: 'Click here to start sync',
                child: IconButton(
                  icon: Icon(Icons.email),
                  onPressed: () { },
                ),
              ),
`

**Comment by mtrfnvwork** [comment]
Did you find a solution?

**Comment by maxwellmandela** [comment]
Closed because it resulted from incorrect implementation

**Comment by MartiSilvio** [comment]
what was the issue?
