### ISSUE TITLE
Requesting Information about Height and Width

### ISSUE THREAD

**Issue by pranav-solutelabs** [SimformSolutionsPvtLtd/flutter_showcaseview#114]
Hi, can you please help me in knowing what is the use of Height and Width params in Showcase.withWidget constructor

For example if I give them 0 and 0 where it should be in accordance to the package, should it be at the center of the current to be highlighted widget ?

**Comment by vatsaltanna** [comment]
Hi @pranav-solutelabs, Height and Width parameter in Showcase.withWidget is used to place content which is provided in container parameter and it is center aligned. and yes if it's 0 then it will start from the center.

**Comment by vatsaltanna** [comment]
I hope that resolves your query. Closing this for now. Feel free to reopen if you need any more info.
