### ISSUE TITLE
tooltip size

### ISSUE THREAD

**Issue by frederic-orlando** [SimformSolutionsPvtLtd/flutter_showcaseview#117]
Tooltip always stretch after having more than certain characters or linebreak

I'm trying to make multiline description
expected:
![image](https://user-images.githubusercontent.com/50309351/123525151-ea88cf00-d6f8-11eb-8232-1cf5d22e5b17.png)

no linebreak: 
![image](https://user-images.githubusercontent.com/50309351/123525259-81ee2200-d6f9-11eb-8532-9c5dee139bc4.png)

with \n:
![image](https://user-images.githubusercontent.com/50309351/123525129-d644d200-d6f8-11eb-9c04-e8777b22fdc8.png)

first line only:
![image](https://user-images.githubusercontent.com/50309351/123525277-9f22f080-d6f9-11eb-9ee8-3c8783e2e24d.png)

short description with same showcase properties:
![image](https://user-images.githubusercontent.com/50309351/123525297-bf52af80-d6f9-11eb-87c7-ac88ecd8bee7.png)

short with \n:
![image](https://user-images.githubusercontent.com/50309351/123525323-ea3d0380-d6f9-11eb-92c8-4056685ccef2.png)

**Smartphone:**
 - Device: Pixel 3

**Comment by vatsaltanna** [comment]
Hello @frederic-orlando, 

We recently have released a new version of the showcase view package `showcaseview: ^1.1.0`. please try the new version. Your problem should have been solved in the new release.

**Comment by vatsaltanna** [comment]
Feel free to reopen if it is still happening for you.
