### ISSUE TITLE
onToolTipClick => go on to next showcase

### ISSUE THREAD

**Issue by nietsmmar** [SimformSolutionsPvtLtd/flutter_showcaseview#119]
I am using `Showcase.withWidget` and when a click is done on my Widget, I'd like to go on to the next showCase key. 

I could do my own ClickListener on my Widget of course. But how can I tell the showcase to continue? The `disposeOnTap` option only closes but does not continue to next one.

Thanks a lot!

**Comment by vatsaltanna** [comment]
Hi, @nietsmmar

You can achieve your expected behaviour with this call `ShowCaseWidget.of(context)!.completed(showCase_key);` on any gesture call.

**Comment by vatsaltanna** [comment]
I hope that resolves your query. Closing this for now. Feel free to reopen if you need any more info.

**Comment by nietsmmar** [comment]
Thanks a lot! This solved my issue.
