### ISSUE TITLE
Showcases should automatically schedule

### ISSUE THREAD

**Issue by VKBobyr** [SimformSolutionsPvtLtd/flutter_showcaseview#126]
**Is your feature request related to a problem? Please describe.**
If I play a showcase while another one is active, the active one will be replaced

**Describe the solution you'd like**
If I play a showcase while there's an active one, the showcase should start after the current one is done

**Describe alternatives you've considered**
Currently using my own scheduler:
```dart
class AesOuterTutorialWrapper extends HookWidget {
  final Widget child;

  const AesOuterTutorialWrapper({
    Key? key,
    required this.child,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final scheduler = useMemoized(() => AesTutorialScheduler());

    return Provider.value(
      value: scheduler,
      child: ShowCaseWidget(
        onFinish: scheduler.onDone,
        builder: Builder(builder: (context) {
          scheduler.context = context;
          return child;
        }),
      ),
    );
  }
}

class AesTutorialScheduler {
  BuildContext? context;
  final List<List<GlobalKey>> _queue = [];
  bool running = false;

  void onDone() {
    running = false;
    _tik();
  }

  void add(List<GlobalKey> keys) {
    _queue.add(keys);
    _tik();
  }

  void _tik() async {
    if (running || _queue.isEmpty) return;
    running = true;
    final keys = _queue.removeLast();
    await Future.delayed(Duration.zero);
    ShowCaseWidget.of(context!)!.startShowCase(keys);
  }
}
```

**Additional context**
None

**Comment by vatsaltanna** [comment]
Hi @VKBobyr , Showcase view is designed in a view where you will not require multiple ShowCaseWidget instance, you can use multple showcaseview with key when go for the next showcase view with next() function available (in the latest version of showcaseview) for the next feature showcase.

Closing this for now, feel free to reopen this for any other assistance or issue.
