### ISSUE TITLE
Highlighting not working in version 1.1.0

### ISSUE THREAD

**Issue by Ramkrishna-egov** [SimformSolutionsPvtLtd/flutter_showcaseview#129]
I have wrapped my widget inside showcase
Showcase(
                    key: _one,
                    title: 'Title',
                    description: 'Desc',
                    child: InkWell(
                      onTap: () {},
                      child: Text(
                        'Flutter Notification',
                        style: TextStyle(
                            fontSize: 25, fontWeight: FontWeight.w600),
                      ),
                    ),
                  ),
Its the same example which was in git repo,  I am using it in my file, but the highlight widget is not working
![Highlight not workingg](https://user-images.githubusercontent.com/85437265/129877317-73e56079-2359-4d0b-8681-82e47b7f6a12.png)

**Comment by vatsaltanna** [comment]
Hello @Ramkrishna-egov , Can you please share more details like which platform are you using to run this app? what are other modifications that you have made in the project as I believe the same screen is working as expected in the example? it will be much more helpful for us if you can share the full file content and code related to the showcaseview.

**Comment by Ramkrishna-egov** [comment]
> Hello @Ramkrishna-egov , Can you please share more details like which platform are you using to run this app? what are other modifications that you have made in the project as I believe the same screen is working as expected in the example? it will be much more helpful for us if you can share the full file content and code related to the showcaseview.

**Comment by Ramkrishna-egov** [comment]
> Hello @Ramkrishna-egov , Can you please share more details like which platform are you using to run this app? what are other modifications that you have made in the project as I believe the same screen is working as expected in the example? it will be much more helpful for us if you can share the full file content and code related to the showcaseview.
I am using Android Studio, and I ran the app in Chrome(web), First I tried running your repo only, it worked perfectly fine, But when I copied your example code and tried to run it in my app, the highlighting of widget was not working, In the inbuilt Android emulator its working perfectly fine, Why such issues arising?? Is it not compatible for every device ??
