### ISSUE TITLE
show Unhandled Exception: Null check operator used on a null value error

### ISSUE THREAD

**Issue by P-B1101** [SimformSolutionsPvtLtd/flutter_showcaseview#138]
**Describe the bug**
When I update package to version 1.1.1 and run the app, it show this error in console and the showcase itself not working.

**Console**

`
/flutter ( 2417): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 2417): #0      _OverlayBuilderState.addToOverlay
package:showcaseview/src/layout_overlays.dart:163
E/flutter ( 2417): #1      _OverlayBuilderState.showOverlay
package:showcaseview/src/layout_overlays.dart:155
E/flutter ( 2417): #2      _OverlayBuilderState.initState.<anonymous closure>
package:showcaseview/src/layout_overlays.dart:120
E/flutter ( 2417): #3      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1144
E/flutter ( 2417): #4      SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1090
E/flutter ( 2417): #5      SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:998
E/flutter ( 2417): #6      _rootRun (dart:async/zone.dart:1354:13)
E/flutter ( 2417): #7      _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter ( 2417): #8      _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter ( 2417): #9      _invoke (dart:ui/hooks.dart:163:10)
E/flutter ( 2417): #10     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
E/flutter ( 2417): #11     _drawFrame (dart:ui/hooks.dart:126:31)
`

**Comment by vatsaltanna** [comment]
@P-B1101 can you please share snippet code in which you are facing this issue?

**Comment by P-B1101** [comment]
```
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return ShowCaseWidget(
      builder: Builder(builder: (context) {
        return MaterialApp(
          title: 'Flutter Demo',
          theme: ThemeData(
            primarySwatch: Colors.blue,
          ),
          home: const MyHomePage(title: 'Flutter Demo Home Page'),
        );
      }),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

const int showCaseTriger = 5;

class _MyHomePageState extends State<MyHomePage> {
  final GlobalKey gKey = GlobalKey();
  int _counter = 0;

  void _incrementCounter() {
    if (_counter > showCaseTriger) return;
    if (_counter == showCaseTriger) {
      ShowCaseWidget.of(context)?.startShowCase([gKey]);
      return;
    }
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Showcase(
              title: 'Test Title\n',
              description: 'Test Description',
              key: gKey,
              overlayColor: Theme.of(context).primaryColor,
              showcaseBackgroundColor: Colors.transparent,
              showArrow: false,
              disableAnimation: true,
              contentPadding: const EdgeInsets.only(
                top: 8,
                bottom: 8,
                left: 16,
                right: 16,
              ),
              child: Text(
                'Push the button ${showCaseTriger - _counter} more times to trigger the show case.',
              ),
              disposeOnTap: true,
              onTargetClick: () {},
            )
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

**Comment by vatsaltanna** [comment]
@P-B1101 We identify the reason of error that you are facing with your widget tree 
please place ShowCaseWidget inside MaterialApp.
 
Your Current Widget Tree:
`main() -> ShowCaseWidget -> MaterialApp -> MyHomePage`

Update widget tree with below sequence:
`main() -> MaterialApp -> ShowCaseWidget -> MyHomePage`

**Comment by vatsaltanna** [comment]
I am closing this issue for now, feel free to reopen this issue if the given solution is not working.

**Comment by P-B1101** [comment]
Thank you,  your solution fix the issue :) .
