### ISSUE TITLE
Manual step completion

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [SimformSolutionsPvtLtd/flutter_showcaseview#144]
Hello, 

I would like to use your package to onboard users. But I need something like strict onboarding. It would include:

1. Possibility Manually mark step as completed
2. Steps should be not barrier dismissible
3. Possibility to group steps to feature
4. Possibility to mark feature as completed

Scenario would be following:
User is walked through features step by step not allowing to close steps until action, described in the step, taken. Feature onboarding marked as completed when whole steps are completed otherways feature showcase starts from beginning when app is opened again. 

Let me know what do you think guys 🙂

Thanks

**Comment by jigarfumakiya** [comment]
Any update on this?

**Comment by shwetachauhan-simform** [comment]
@vytautas-pranskunas- , @jigarfumakiya : We have below option when you create **_Showcase_**: 

> disposeOnTap: true

aren't it working working in your case?? I mean if you set this as true, show whenever you are on tour and want to dismiss in between then you can click on tooltip and it will dismiss whole tour.

Let us know if this is not your case and not working for you

**Comment by vatsaltanna** [comment]
Hi @jigarfumakiya @vytautas-pranskunas- , we have now option to disable barrier dismiss in latest version of `showcaseview: 1.0.8` . you can use that for your feature request.

Closing this for now, feel free to reopen this if issue is still there.
