### ISSUE TITLE
Custom tooltip position

### ISSUE THREAD

**Issue by erperejildo** [SimformSolutionsPvtLtd/flutter_showcaseview#152]
How can I set this manually? Sometimes it doesn't look ok:

![Screenshot_1633991477](https://user-images.githubusercontent.com/5629919/136863013-e72fbdd0-bfa6-40f3-9c5c-7343d46ed9ec.png)

**Comment by erperejildo** [comment]
without any change this still looking wrong. Please, let me know how can I change the position manually

**Comment by vatsaltanna-simformsolutions** [comment]
@erperejildo Sorry for the late reply, We are trying to reproduce this issue, it will be very much helpful if you can share code snippet for this and also currently we don't have functionality to provide manual position but surely we will add this in our feature list soon.

**Comment by vatsaltanna** [comment]
@erperejildo Sorry for the late reply, We are trying to reproduce this issue, it will be very much helpful if you can share code snippet for this and also currently we don't have functionality to provide manual position but surely we will add this in our feature list soon.

**Comment by erperejildo** [comment]
> @erperejildo Sorry for the late reply, We are trying to reproduce this issue, it will be very much helpful if you can share a code snippet for this and also currently we don't have the functionality to provide manual position but surely we will add this in our feature list soon.

you can easily replicate it by showing sometime at the bottom of the screen (or maybe below 50% of the height). Can share a screenshot of what you see?

**Comment by vatsaltanna** [comment]
I have checked on the example available on the repo itself, it also has one widget that is on the bottom, the floating action button. it automatically takes the tooltip on the top when there is not enough space at the bottom.

![image](https://user-images.githubusercontent.com/25323183/144372798-2577d878-f3c0-4d90-a32c-39ad6e89b429.png)

**Comment by erperejildo** [comment]
My guess is that at some point in the screen it puts the label below the widget but we still have no visibility. For that exactly that's a bottom element that clearly needs to be on top. Can you try with another floating element from top to bottom? I'll try to reproduce it from my side as well

**Comment by proninyaroslav** [comment]
I think these are similar problems: https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/issues/174#issuecomment-986962218

**Comment by proninyaroslav** [comment]
As a workaround, I use `Stack` and `SizedBox.shrink()` inside, which I can put in a convenient place.

**Comment by erperejildo** [comment]
> #174 (comment)

could you provide an example please?

**Comment by proninyaroslav** [comment]
@erperejildo 
Tested on Pixel 4 XL emulator:

```Dart
import 'package:flutter/material.dart';
import 'package:showcaseview/showcaseview.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: ShowCaseWidget(
        builder: Builder(
          builder: (context) => const MyHomePage(),
        ),
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _key = GlobalKey();

  @override
  void initState() {
    super.initState();

    WidgetsBinding.instance?.addPostFrameCallback(
      (_) => ShowCaseWidget.of(context)?.startShowCase([_key]),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Container(
        margin: const EdgeInsets.all(45.0),
        child: Showcase(
          key: _key,
          description: 'My tooltip',
          child: Container(
            color: Colors.green,
          ),
        ),
      ),
    );
  }
}
```
![Screenshot_1638863347](https://user-images.githubusercontent.com/7840559/144988246-ab97b9d1-db9c-4a3c-93e3-61fbc1686b81.png)

**Comment by erperejildo** [comment]
> @erperejildo Tested on Pixel 4 XL emulator:
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:showcaseview/showcaseview.dart';
> 
> void main() {
>   runApp(const MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   const MyApp({Key? key}) : super(key: key);
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter Demo',
>       home: ShowCaseWidget(
>         builder: Builder(
>           builder: (context) => const MyHomePage(),
>         ),
>       ),
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   const MyHomePage({Key? key}) : super(key: key);
> 
>   @override
>   State<MyHomePage> createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> {
>   final _key = GlobalKey();
> 
>   @override
>   void initState() {
>     super.initState();
> 
>     WidgetsBinding.instance?.addPostFrameCallback(
>       (_) => ShowCaseWidget.of(context)?.startShowCase([_key]),
>     );
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(),
>       body: Container(
>         margin: const EdgeInsets.all(45.0),
>         child: Showcase(
>           key: _key,
>           description: 'My tooltip',
>           child: Container(
>             color: Colors.green,
>           ),
>         ),
>       ),
>     );
>   }
> }
> ```
> 
> ![Screenshot_1638863347](https://user-images.githubusercontent.com/7840559/144988246-ab97b9d1-db9c-4a3c-93e3-61fbc1686b81.png)

and where exactly do you put those widgets to fix it?

**Comment by proninyaroslav** [comment]
@erperejildo 
Something like this:
```Dart
Stack(
  children: [
    Align(
      alignment: Alignment.topCenter,
      child: Showcase(
        key: _key,
        description: 'My tooltip',
        child: SizedBox.shrink(),
      ),
    ),
    Center(
      child: Container(
        color: Colors.green,
      ),
    )
  ],
);
```
Yes, we will not have an overlay in this case, but this way we can position the tooltip as we like.
