### ISSUE TITLE
Create showcase for widget with dynamic size

### ISSUE THREAD

**Issue by erperejildo** [SimformSolutionsPvtLtd/flutter_showcaseview#153]
I've got a `Grid` inside a `Flexible`. How could I apply a showcase for it?

**Comment by meetjanani-simformsolutions** [comment]
@erperejildo  could you please share more info like how you are using currently & what type of issues are facing.

**Comment by d9media** [comment]
hey @erperejildo  I wrapped up my child widget within the row in a sizedbox but Flutter is throwing Incorrect use of ParentDataWidget errors. So annoying! Did you end up solving this somehow?

**Comment by erperejildo** [comment]
> hey @erperejildo I wrapped up my child widget within the row in a sizedbox but Flutter is throwing Incorrect use of ParentDataWidget errors. So annoying! Did you end up solving this somehow?

nope. I gave up

**Comment by d9media** [comment]
Oh no! Sorry to hear that!

I ended up solving it by passing my own ShowcaseOptions object to the flexible widget. If that is present in the widget, I show it above the container. Works.

`class ShowcaseOptions {
  final GlobalKey globalKey;
  final String key;
  final String title;
  final String description;

  ShowcaseOptions(
      {required this.globalKey,
      required this.key,
      required this.title,
      required this.description});
}

class ShowcaseSteps {
  final GlobalKey mainMenu = GlobalKey();
  final GlobalKey locationChip = GlobalKey();
  final GlobalKey timecardWork = GlobalKey();
  final GlobalKey timecardBreak = GlobalKey();
  final GlobalKey timeButtons = GlobalKey();
  final GlobalKey weeklyNavigation = GlobalKey();
  final GlobalKey weeklyPending = GlobalKey();
  final GlobalKey weeklyEditEntry = GlobalKey();
}
`

In the flexible widget:
```
TimeCard(
                        title: "",
                        isRunning: _currentTimeEntry != null &&
                            !_currentTimeEntry.isPaused,
                        currentTime: _currentTimeEntry?.workTime ??
                            const Duration(minutes: 0),
                        targetTime: _employeeProfile?.regularWorkingHours ??
                            const Duration(hours: 8),
                        showcaseOptions: ShowcaseOptions(
                            description:
                                "showcase desc",
                            title: "showcase title",
                            globalKey: _showcaseSteps.timecardWork,
                            key: "timecard_work"),
                        stepping: {
                          0: Colors.grey,
                          50: ConsilmedColors.highlight,
                          100: ConsilmedColors.success
                        },
                      ),

```

and inside the flexible widget (timecard):

  @override
  Widget build(BuildContext context) {
    final Widget innerContent = Container(
      height: compactHeight ? 150 : 200,
      // and other content
    );

    return Expanded(
      child: showcaseOptions == null
          ? innerContent
          : Showcase(
              key: showcaseOptions!.globalKey,
              description: showcaseOptions!.description,
              title: showcaseOptions!.title,
              child: innerContent),
    );
``

**Comment by d9media** [comment]
Oh no! Sorry to hear that!

I ended up solving it by passing my own ShowcaseOptions object to the flexible widget. If that is present in the widget, I show it above the container. Works.

```
class ShowcaseOptions {
  final GlobalKey globalKey;
  final String key;
  final String title;
  final String description;

  ShowcaseOptions(
      {required this.globalKey,
      required this.key, // <-- I was gonna use this for globalstorage but didnt end up use it currently
      required this.title,
      required this.description});
}

class ShowcaseSteps {
  final GlobalKey mainMenu = GlobalKey();
  final GlobalKey locationChip = GlobalKey();
  final GlobalKey timecardWork = GlobalKey();
  final GlobalKey timecardBreak = GlobalKey();
  final GlobalKey timeButtons = GlobalKey();
  final GlobalKey weeklyNavigation = GlobalKey();
  final GlobalKey weeklyPending = GlobalKey();
  final GlobalKey weeklyEditEntry = GlobalKey();
}
```


In the flexible widget:
```
TimeCard(
      title: "",
      showcaseOptions: ShowcaseOptions(
             description: "showcase desc",
             title: "showcase title",
             globalKey: _showcaseSteps.timecardWork,
             key: "timecard_work"),
     // other properties
         ),

```

and inside the flexible widget (timecard):

  ```
@override
  Widget build(BuildContext context) {
    final Widget innerContent = Container(
      height: compactHeight ? 150 : 200,
      // and other content
    );

    return Expanded(
      child: showcaseOptions == null
          ? innerContent
          : Showcase(
              key: showcaseOptions!.globalKey,
              description: showcaseOptions!.description,
              title: showcaseOptions!.title,
              child: innerContent),
    );



```

I agree fixed size parameters might be easier though

**Comment by aditya-css** [comment]
Hi @erperejildo, Seems like you have wrapped `Showcase` over the `Flexible` and `Grid.count` widget. 
The error is specifically saying that only: "Incorrect use of ParentDataWidget"...... "Typically, Flexible widgets are placed directly inside Flex widgets".
Please have the `Flexible` widget as parent of `Showcase` instead and your issue would be resolved.
