### ISSUE TITLE
Showcase Speed Dial Children from flutter_speed_dial package

### ISSUE THREAD

**Issue by nighteye1** [SimformSolutionsPvtLtd/flutter_showcaseview#155]
**Describe the bug**

**To Reproduce**
1. Create a speed dial fab and add 3-4 speed dial children. For each children wrap its child (an image in my case) with showcase widget.
2. When I tap on fab icon, it shows all the options and at this point I want to showcase all the children one by one.
3. I have tried to solve this issue in onOpen method of SpeedDial which is executed when speed dial is opened.
4. If I wrap a speed dial child's child with showcase, I get an error  'Null check operator used on a null value'

The error refers to activeWidgetId parameter in showcase_widget.dart (Attaching screenshot)

**Expected behavior**
Showcase should highlight all the speed dial children one by one.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS, Android

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 14.7
 
[Screen Shot 2021-10-15 at 3 19 17 PM](https://user-images.githubusercontent.com/61348072/137472633-26d2347c-6c2c-4da2-8a40-43cade21b250.png)

**Comment by vatsaltanna** [comment]
Hello @nighteye1 , we have released a new version of this package [showcaseview: 1.1.4](https://pub.dev/packages/showcaseview), which might have fixes related to this issue, so can you please test this in latest version and update the status on this same thread?
