### ISSUE TITLE
Showcase hides in A scrollable Widget

### ISSUE THREAD

**Issue by cyuket** [SimformSolutionsPvtLtd/flutter_showcaseview#157]
**Describe the bug**

Showcase shows in a widget that is not visible at the moment if it is in a scrollable widget and the showcase is also not visible

**Comment by MaxiStefan** [comment]
Any workarounds for this?

**Comment by YDA93** [comment]
My current workaround:

You must use a **scroll controller** as well as adding **onTargetClick** and **disposeOnTap** properties to Showcase.

You will scroll exactly to the wanted element by it's Showcase key. 

Example:

```
return Showcase(
  onTargetClick: () async {
       await scrollController.position.ensureVisible(
         secondShowCaseKey.currentContext!.findRenderObject()!,
         alignment: 0.0,
         duration: const Duration(milliseconds: 100),
         curve: Curves.linear,
        );
        ShowCaseWidget.of(context)?.next();
  },
  disposeOnTap: false,
  key: firstShowCaseKey,
  title: 'title',
  description: 'description',
  child: child,
)
```

**Comment by YDA93** [comment]
If we can add a scroll controller to  Showcase and make this automatically triggered by package would be perfect.

Maybe add null safety to avoid bugs something like:

```
final _renderObject =
                secondShowCaseKey.currentContext?.findRenderObject();

if (_renderObject != null) {
    await scrollController.position.ensureVisible(
    _renderObject,
    alignment: 0.0,
    duration: const Duration(milliseconds: 100),
    curve: Curves.linear,
   );
}

ShowCaseWidget.of(context)?.next();
```

**Comment by DhavalRKansara** [comment]
@cyuket  @MaxiStefan  @mhilalsh showcaseview has added feasibility of [Scrolling to active showcase](https://pub.dev/packages/showcaseview#scrolling-to-active-showcase) and [Enable Auto Scrolling](https://pub.dev/packages/showcaseview#enable-auto-scrolling) in the latest release can you please check with the same. I guess your issue will be fixed by using it.

**Comment by DhavalRKansara** [comment]
This issue seems to be solved in the latest version of [showcaseview](https://pub.dev/packages/showcaseview). Closing this, for now, feel free to reopen this if the issue still persists.
