### ISSUE TITLE
Arrow pointing dow

### ISSUE THREAD

**Issue by kelvindominguez1595** [SimformSolutionsPvtLtd/flutter_showcaseview#159]
Why can't you put the arrow pointing down? or what would be the form

**Comment by vatsaltanna** [comment]
Closing this, for now, feel free to reopen if any other information is required.

**Comment by Dev291199** [comment]
Is there any option where i can give the dynamic position to the arrow? For example I want the arrow to be at top-left corner. Also my target widget is at the center of the screen
