### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by cirediew** [SimformSolutionsPvtLtd/flutter_showcaseview#163]
When using a `Showcase` in a `ReorderableListView` I get the exception `Null check operator used on a null value` when reordering the first item in the list.

<details>
<summary>Exception</summary>

> ======== Exception caught by widgets library =======================================================
> The following _CastError was thrown while rebuilding dirty elements:
> Null check operator used on a null value
> 
> The relevant error-causing widget was: 
>   Showcase-[GlobalKey#6d359] Showcase:file:///Users/user/development/test/test_app/lib/my_list.dart:32:13
> When the exception was thrown, this was the stack: 
> #0      ShowCaseWidget.activeTargetWidget (package:showcaseview/src/showcase_widget.dart:46:70)
> #1      _ShowcaseState.showOverlay (package:showcaseview/src/showcase.dart:180:39)
> #2      _ShowcaseState.didChangeDependencies (package:showcaseview/src/showcase.dart:173:5)
> #3      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4837:13)
> #4      Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
> #5      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:33)
> #6      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
> #7      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
> #8      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
> #9      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
> #10     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
> #14     _invoke (dart:ui/hooks.dart:166:10)
> #15     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
> #16     _drawFrame (dart:ui/hooks.dart:129:31)
> (elided 3 frames from dart:async)
> The element being rebuilt at the time was index 21 of 38: Showcase-[GlobalKey#6d359]
>   dirty
>   dependencies: [_EffectiveTickerMode]
>   state: _ShowcaseState#04f30(tickers: tracking 1 ticker)
> 
> 
> ======== Exception caught by scheduler library =====================================================
> The following assertion was thrown during a scheduler callback:
> buildScope missed some dirty elements.
> 
> 
> This probably indicates that the dirty list should have been resorted but was not.
> 
> The list of dirty elements at the end of the buildScope call was: 
>   : Showcase-[GlobalKey#6d359]
>     dirty
>     dependencies: [_EffectiveTickerMode]
>     state: _ShowcaseState#04f30(tickers: tracking 1 ticker)
>   : ListTile-[<'0'>]
>     dependencies: [_InheritedTheme, _LocalizationsScope-[GlobalKey#cb121], Directionality]
>   : Text
>     "Item 0"
>     dependencies: [DefaultTextStyle, MediaQuery]
>   ...
> When the exception was thrown, this was the stack: 
> #0      BuildOwner.buildScope.<anonymous closure> (package:flutter/src/widgets/framework.dart:2655:11)
> #1      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2662:8)
> #2      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
> #3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
> #4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
> #5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
> #6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
> #10     _invoke (dart:ui/hooks.dart:166:10)
> #11     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
> #12     _drawFrame (dart:ui/hooks.dart:129:31)
> (elided 3 frames from dart:async)
> 

</details>

My code:

```dart
import 'package:flutter/material.dart';
import 'package:showcaseview/showcaseview.dart';
import 'package:test_app/my_list.dart';

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: ShowCaseWidget(
        builder: Builder(
          builder: (_) => const MyList(),
        ),
      ),
    );
  }
}
```

```dart
import 'package:flutter/material.dart';
import 'package:showcaseview/showcaseview.dart';

class MyList extends StatefulWidget {
  const MyList({Key? key}) : super(key: key);

  @override
  _MyListState createState() => _MyListState();
}

class _MyListState extends State<MyList> {
  final List<int> _items = List<int>.generate(50, (int index) => index);
  final GlobalKey _one = GlobalKey();

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance!.addPostFrameCallback(
        (_) => ShowCaseWidget.of(context)!.startShowCase([_one]));
  }

  @override
  Widget build(BuildContext context) {
    final ColorScheme colorScheme = Theme.of(context).colorScheme;
    final Color oddItemColor = colorScheme.primary.withOpacity(0.05);
    final Color evenItemColor = colorScheme.primary.withOpacity(0.15);

    return ReorderableListView(
      children: <Widget>[
        for (int index = 0; index < _items.length; index++)
          if (index == 0)
            Showcase(
              key: _one,
              description: 'MyDescription',
              child: ListTile(
                key: Key('$index'),
                tileColor: _items[index].isOdd ? oddItemColor : evenItemColor,
                title: Text('Item ${_items[index]}'),
              ),
            )
          else
            ListTile(
              key: Key('$index'),
              tileColor: _items[index].isOdd ? oddItemColor : evenItemColor,
              title: Text('Item ${_items[index]}'),
            ),
      ],
      onReorder: (int oldIndex, int newIndex) {
        setState(() {
          if (oldIndex < newIndex) {
            newIndex -= 1;
          }
          final int item = _items.removeAt(oldIndex);
          _items.insert(newIndex, item);
        });
      },
    );
  }
}

```

**Comment by SalishKumar** [comment]
@cirediew did you find any solution?

**Comment by cirediew** [comment]
@SalishKumar Unfortunately I have not. To be fair I've removed the showcase from the list for now.

**Comment by cirediew** [comment]
@vatsaltanna-simformsolutions @vatsaltanna Thank you for fixing it. Do you know when this will be released?

**Comment by vatsaltanna** [comment]
@cirediew we will try to release it by EOD.

**Comment by vatsaltanna** [comment]
Hi @cirediew, New version of [showcaseview 1.1.4](https://pub.dev/packages/showcaseview) is live.
