### ISSUE TITLE
Custom widget parameters

### ISSUE THREAD

**Issue by Wian-TMC** [SimformSolutionsPvtLtd/flutter_showcaseview#164]
**Describe the bug**
There seems no way to centre the custom widget, or select its alignment.

**To Reproduce**
1. Create a custom widget of a specific width
2. Try to centre the custom widget 

**Screenshots**
![image](https://user-images.githubusercontent.com/72802049/140875391-723abf99-10d1-4e89-9c68-8136c5f14e10.png)

**Additional context**
I would like the widget to float in the centre (horizontally)

**Comment by vatsaltanna-simformsolutions** [comment]
@Wian-TMC I hope above information solved your issue. if your issue still persist than feel free to reopen this issue.

**Comment by SteveCruise** [comment]
Bug! please fix it.

**Comment by vatsaltanna** [comment]
@SteveCruise  Have you tried this answer? it will solve your issue.

> @Wian-TMC : For that can you please try **_Showcase.withWidget_** and **_custom widget (container)_** width same??
> 
> ```
> child: Showcase.withWidget(
>           width: 155,
>           height: 45,
>           key: _three,
>           description: 'Tap to check mail',
>           disposeOnTap: true,
>           container: Container(               // Here, as a _container_ you will use your custom widget and pass width same as _Showcase.withWidget_
>               width: 155,
>           )
> )
> ```
