### ISSUE TITLE
Add an onActive function to the Showcase widget.

### ISSUE THREAD

**Issue by tobiasht** [SimformSolutionsPvtLtd/flutter_showcaseview#167]
**Is your feature request related to a problem?**
When getting to step X in my tutorial, I would like to slightly change the UI. For example navigating to another screen. At the moment there is no function called when getting to specific step in the "tutorial". Would be very helpful to add this to the Showcase widget.

**Describe the solution you'd like**
I want a function that automatically triggers when reaching a step. 

```dart
// Example
void Function()? onActive 
```

**Describe alternatives you've considered**
It is possible to trigger a new tutorial on the end the last, but this is a lot of hassle for minor UI changes.

**Comment by vatsaltanna** [comment]
Hi @tobiasht, The functionality you are requesting is already available. you can use `onStart` or `onComplete` parameters of `ShowCaseWidget` to get the step where the current showcase is.

Closing this, for now, feel free to reopen this issue if you need any other information related to this functionality.
