### ISSUE TITLE
Positioning of tooltip over the screen

### ISSUE THREAD

**Issue by Ahmed-elshorbagy** [SimformSolutionsPvtLtd/flutter_showcaseview#174]
when using show case with large widgets it is not show on the screen 
why can't be used with Alignment to position it correctly over screen by using (0,0) for top left and (1,1) for bottom right
thanks in advance

**Comment by vatsaltanna** [comment]
Can you please elaborate with more details?

**Comment by Ahmed-elshorbagy** [comment]
if we wrap large widget with show case its tooltip may be out of the screen so why can't we position it over the widget itself and if we want top position it precisely we can by using Alignment or positioned widget 
thanks in advance @vatsaltanna 
![showcase](https://user-images.githubusercontent.com/20170741/144076247-aa2657b5-a339-4d43-8369-0076835d0734.PNG)
![Screenshot_1638284348](https://user-images.githubusercontent.com/20170741/144076206-80972f32-99b5-4443-8637-8c912a63f75b.png)

**Comment by vatsaltanna** [comment]
I got your point but it seems that there is no proper use case of this functionality as there are very rare chances where the widget will be near to full screen and it needs to be highlighted. it will be very much helpful if you can share the use case currently you are having.

**Comment by proninyaroslav** [comment]
I faced a similar problem. I just wrapped a large widget, which is located in the center

![Screenshot_1638809598](https://user-images.githubusercontent.com/7840559/144888141-b069293b-a353-4c60-aeb6-dbe968fe39a3.png)

**Comment by proninyaroslav** [comment]
As a workaround, I use `Stack` and `SizedBox.shrink()` inside, which I can put in a convenient place.

**Comment by Ahmed-elshorbagy** [comment]
I used a similar workaround also with stack i used an empty container and positioned it at the desired position and made the color of showcase background as transparent but i think this is not a good approach

**Comment by abhu66** [comment]
I solved this problem by reducing the height of the screen in ShowCase.withWidget(
...
height:MediaQuery.of(context).size.hight - 400 or any;
)

**Comment by rmahmadkhan** [comment]
@abhu66 this design is dope 🔥
for inspiration, can you please share the code behind custom widget and the how you positioned it?

**Comment by kaseyrossanderson** [comment]
@vatsaltanna In web we have a side navigation which I want to alert users to and it takes up the full height of the screen at all times regardless of screen size. The tooltip is positionable at either the top or the bottom. It would be nice if you could also choose from the left or the right.. so that in cases like this we can do to the size.

There are several other places in my app that I would use the side instead of on top or bottom and not just when something is taking up the full screen height.

**Comment by abhu66** [comment]
> @abhu66 this design is dope 🔥 for inspiration, can you please share the code behind custom widget and how you positioned it above the target widget?

Sure,

**Comment by Sahil-Simform** [comment]
@Ahmed-elshorbagy,

PR #466 has been raised to address this issue. You can use the branch associated with the PR as a temporary solution until we officially release the fix.

Let me know if you need any assistance!
