### ISSUE TITLE
Looking up a deactivated widget's ancestor is unsafe. 

### ISSUE THREAD

**Issue by amansatija** [SimformSolutionsPvtLtd/flutter_showcaseview#175]
**Describe the bug**
I have a flutter app with multiprovider 
have added showcaseWidget in the home: of material app 
and then the home page has curvedBottomNavBar along with PageView 

in one of the page of the page view i added globalkeys and the showcase widget 
it renders the first time but on navigation item changed it starts to crash with the below  error 

Looking up a deactivated widget's ancestor is unsafe. 

**To Reproduce**
1. add a bottom nav bar with pageview 
2. in one of the pages of the page view add showcase widget with globalkey
3. switch page and come back to this page 

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. emulator android pixel 3a android q]
 - OS: [e.g. android q]

**Additional context**

**Comment by vatsaltanna** [comment]
@amansatija Can you please provide a code snippet in which you are facing this issue?

**Comment by vatsaltanna** [comment]
I am closing this issue for now due to the lack of information. Feel free to reopen this if you face this issue again.
