### ISSUE TITLE
Showcaseview showing white overlay on release apk

### ISSUE THREAD

**Issue by techwithsam** [SimformSolutionsPvtLtd/flutter_showcaseview#184]
Whenever I build the release apk for my app, I always get the white overlay (as shown below) during and after showcase

![a67ad577-6eba-44f7-9974-dd819e6b5255](https://user-images.githubusercontent.com/42917957/153237908-0f49b0bc-6dea-4c8e-be6e-013950713690.jpg)

**Comment by techwithsam** [comment]
I have tried to check through all the package settings to see if there is a way to turn it off but I can't find any. pls kindly look into it. Thanks
@fynntimes @vipulasri @simform-solutions @tejas-ardeshna

**Comment by techwithsam** [comment]
Error log!
![image](https://user-images.githubusercontent.com/42917957/153243937-13322ead-6a3f-4d1a-a254-1df375d837c0.png)

**Comment by DevarshRanpara** [comment]
Hi @techwithsam 
We will verify this issue at our end, Can you please share code snippet for how you are using this plugin, For clear visibelity?

**Comment by vatsaltanna** [comment]
Hi @techwithsam, We check this in release mode and it works perfectly fine on our end though, This seems to be the issue on the UI part of the application, showcase view basically takes the widget that the user provides to display so if that widget is broken then showcase view will also fail to render.

I am closing this for now. if the issue still persists and you require any information then feel free to reopen this.
