### ISSUE TITLE
How to use showcaseview with stacked state management.

### ISSUE THREAD

**Issue by vontdeux** [SimformSolutionsPvtLtd/flutter_showcaseview#187]
Hi, is it possible to use stacked (https://pub.dev/packages/stacked) with showcaseview (https://pub.dev/packages/showcaseview) ?

what i've tried, I used onModelReady
onModelReady: (model) => model.init(context),

and inside init, i called startShowCase

void init(BuildContext context) {
    //delay a little bit
    Future.delayed(const Duration(milliseconds: 500), () {
      startShowCase(context);
    });
  }
but it doesn't seems to be working.

**Comment by vatsaltanna** [comment]
Hi @vontdeux ,  Could you please share the full sample code snippet as well as the the stacktrace of the error you are facing?

Thanks

**Comment by ruchitmavani** [comment]
@vontdeux Make your stateless widget -> Stateful because showcaseview uses keys to display the tutorial. I know it's defeat the purpose of stacked state management since you already have builder in the body but for now you can make it stateful and it will work

**Comment by ziqq** [comment]
> @vontdeux Make your stateless widget -> Stateful because showcaseview uses keys to display the tutorial. I know it's defeat the purpose of stacked state management since you already have builder in the body but for now you can make it stateful and it will work

Yap it work in this variant only

**Comment by vatsaltanna** [comment]
I am assuming the solution provided by @ruchitmavani  solves the problem. Thanks, @ruchitmavani, for your valuable inputs. I'm closing this issue for now, but feel free to reopen this issue if the issue still persists after the solution.
