### ISSUE TITLE
Showcase does nothing on complex widget

### ISSUE THREAD

**Issue by mhilalsh** [SimformSolutionsPvtLtd/flutter_showcaseview#194]
I'm trying to wrap a complex widget in my page in a Showcase widget but the showcase works and does nothing, no showcase appears.

**Comment by vatsaltanna** [comment]
Hi @mhilalsh, it will be very much helpful to us to solve your issue if you could share more information like screenshots and code snippets of the problem you are facing?

Thanks

**Comment by mhilalsh** [comment]
Hi @vatsaltanna, 
I'm very sorry I won't be able to show you my full code but here's my full case, 
I have a complex widget called **datatable** that consists of :
column (
       children [
                row (
                       children [
                                Text(), 
                                 3 x IconButtons()
                                     ]
                        ),
                HorizontalDataTable()        
]
)

this widget is the last widget in my HomePage build method and I wrapped it in a showcase, I used the showcase wrap each widget in this homepage and I console each showcase key using : 
onStart: (index, key) {
          log('onStart: $index, $key');
        },
onComplete: (index, key) {
          log('onComplete: $index, $key');
        }

all of the showcases work and appear normally but when it comes to the last widget -my datatable- the showcase starts and freezes the ui without doing anything and after clicking on the screen the showcase is completed without showing anything.

I guess that the problem is in the horizontal data table in the widget because everything else works normally, I've used another approach to run the showcase on an empty container and show the table after the showcase completes, if you know a solution to my problem that would be a lot better,
thanks so much.
