### ISSUE TITLE
How can I control the width and height of the shape wrapping my widget in showcase.withwidget 

### ISSUE THREAD

**Issue by mhilalsh** [SimformSolutionsPvtLtd/flutter_showcaseview#199]
I'm using Showcase.withwidget in my code and I want to know How to change width and height of the shape wrapping my widget like this square shape in my screenshot if it's wrapping an Icon or even a text field

![Screenshot (131)](https://user-images.githubusercontent.com/91270937/157031877-c50f0b6a-1f27-4a6e-a735-c51ac842a7a3.png)

**Comment by vatsaltanna-simformsolutions** [comment]
Hi @mhilalsh , you can use `overlayPadding` parameter of `Showcase.withwidget` to achieve your functionality.

PS: Closing this issue. Feel free to reopen this if you need any other information.
