### ISSUE TITLE
.next() and .previous() is not working

### ISSUE THREAD

**Issue by haoyuant** [SimformSolutionsPvtLtd/flutter_showcaseview#200]
I want to present each showcase when a specific even arises, instead of going through the whole showcases by clicking. But when I tried `.startShowCase([_one, _two, _three]);`, after this calling `.next()` or `.previous` didn't do anything. I also tried splitting to `.startShowCase([_one]);`, `.startShowCase([_two]);` and `.startShowCase([_three]);` but the two methods were still not working.

**Comment by ShwetaChauhan18** [comment]
@haoyuant : Can you please share more detail or your code.  It would be great if you share your steps.

**Comment by lolitaCrastaAcko** [comment]
setState(() {
                     bottomNavigationitemindex = index + 1
                    });
                 
                      ShowCaseWidget.of(_showCaseContext!)!.next();
Please try this logic. With setstate it does not work. Showcase widget is hidden.

**Comment by vatsaltanna** [comment]
Hi @lolitaCrastaAcko , Could you please share full sample code snippet in which you are facing this issue? It will be very much helpfull for us to invastigate the issue. 

Thanks

**Comment by vatsaltanna** [comment]
Because of inactivity closing this issue. feel free to reopen this is if you still face this issue in latest version of the package.
