### ISSUE TITLE
Its show me black screen and tooltip. What may be the reason of this behaviour. 

### ISSUE THREAD

**Issue by ps6067966** [SimformSolutionsPvtLtd/flutter_showcaseview#203]

**Comment by ps6067966** [comment]
<img width="223" alt="image" src="https://user-images.githubusercontent.com/26248740/159696290-f102309f-2bcd-41a6-ac1c-c5e42f077851.png">

**Comment by ps6067966** [comment]
<img width="526" alt="image" src="https://user-images.githubusercontent.com/26248740/159696391-d7ba4654-8dc9-4603-afc1-3124ec1bdaf7.png">


Init code.

**Comment by ps6067966** [comment]
Showcase(
                    key: _learnShowcaseKey!,
                    showcaseBackgroundColor: Theme.of(context).primaryColor,
                    titleTextStyle: const TextStyle(
                        fontSize: 20,
                        letterSpacing: 1.2,
                        fontWeight: FontWeight.bold,
                        color: Colors.white),
                    descTextStyle: const TextStyle(
                        fontSize: 15,
                        letterSpacing: 1.2,
                        fontWeight: FontWeight.normal,
                        color: Colors.white),
                    overlayPadding: const EdgeInsets.all(5),
                    contentPadding: const EdgeInsets.all(10),
                    showArrow: true,
                    overlayOpacity: 1,
                    radius: const BorderRadius.all(Radius.circular(10)),
                    description:
                        "Discover bite-sized fun courses on in-demand careers",
                    blurValue: 1,
                    textColor: Colors.black,
                    title: "Learn",
                    child: Icon(Icons.book,
                        size: 30,
                        semanticLabel: 'Learn',
                        color:
                            _selectedIndex == 0 ? Colors.white : Colors.white),
                  )

**Comment by DhavalRKansara** [comment]
@ps6067966  I have checked with your widget and I found you have set `overlayOpacity` and because of it the complete background is getting overlapped there and it shows the black screen to you. You can simply set  `overlayOpacity: 0.75` then it will work fine for you.

Please let me know if you still face the issue.

**Comment by vatsaltanna** [comment]
Hi @ps6067966 , Answer provided by @DhavalRKansara  seems to be the solution for your issue. Closing this issue for now, feel free to reopen this if issue still persist.
