### ISSUE TITLE
Showcase cuts off from the screen if positioned to a relatively centre position

### ISSUE THREAD

**Issue by wilson-christian** [SimformSolutionsPvtLtd/flutter_showcaseview#208]
**Describe the bug**
As shown in attached screenshot, showcase cuts off from the screen. Any particular method to solve this?

**Expected behavior**
Make itself relative to the screen width and shouldn't be cut from any sides.

**Screenshots**
![Simulator Screen Shot - iPhone 13 - 2022-04-08 at 15 06 14](https://user-images.githubusercontent.com/59436377/162507314-428e907e-265c-4d4b-9e49-4a9efbdbc1f6.png)

**Comment by sarope** [comment]
I am also experiencing this issue. Showcase cuts off on both the left and bottom of the screen. Hopefully we'll see a fix soon.

**Comment by CurtlyCritchlow** [comment]
@sarope @wilson-christian,  use the `contentPadding` property to set the required padding to bring the content back on screen as a temporary work around.

**Comment by DhavalRKansara** [comment]
@wilson-christian  @sarope  Can you guys please some code of the implementation in which you guys are facing this type of issues?

**Comment by DhavalRKansara** [comment]
Hi, @KoheiKanagu I have tried the code you provided above and the issue I found is you are using the widget incorrectly and because of the same you are facing the issue, Try the below code and your issue will be resolved. 

```
class Demo extends StatelessWidget {
  const Demo({Key? key}) : super(key: key);

  static const showcaseKey = GlobalObjectKey('value');

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ShowCaseWidget(
          builder: Builder(
            builder: (context) {
              return Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                Showcase(
                    key: showcaseKey,
                    description:
                    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                    child: ElevatedButton(
                      child: const Text('Tips'),
                      onPressed: () {
                        ShowCaseWidget.of(context).startShowCase([
                          showcaseKey,
                        ]);
                      },
                    ),
                  ),
                ],
              );
            },
          ),
        ),
      ),
    );
  }
}
```
