### ISSUE TITLE
Make showcase Run only once on first Installation

### ISSUE THREAD

**Issue by ahmedsaheed** [SimformSolutionsPvtLtd/flutter_showcaseview#209]
Hi, I was wondering if there's a way I could make this showcase run only once when the app is newly installed. From the example in the package, it runs repeatedly whenever the application is opened.

Thanks in advance

**Comment by melikhanhosdogdu** [comment]
Generally, people manage with shared preferences

**Comment by ahmedsaheed** [comment]
@melikhanhosdogdu when you say shared preferences can you elaborate more

**Comment by vatsaltanna** [comment]
Hi @ahmedsaheed , The feature you requested should be handled separately as it doesn't depend on showcase view. as @melikhanhosdogdu suggested you can use shared preferences to store data if user has already visited showcase view or not and based on that next time you can skip the showcase view.

I hope this information helps you. Thanks for using showcase view package.
