### ISSUE TITLE
Highlighting not working in Flutter Web with HTML renderer

### ISSUE THREAD

**Issue by razfazz** [SimformSolutionsPvtLtd/flutter_showcaseview#211]
Highlighting on Flutter Web only works with canvaskit and not html renderer

**Comment by miraklecode** [comment]
same

**Comment by meetjanani-simformsolutions** [comment]
Hello, @razfazz and @miraklecode we found [Open Issue](https://github.com/flutter/flutter/issues/81637) as it's an open issue from the flutter side, we will keep watch on it, once it will be solved in the framework we will update the package with necessary changes.
