### ISSUE TITLE
Add onBackgroundClick or similar

### ISSUE THREAD

**Issue by arndt-s** [SimformSolutionsPvtLtd/flutter_showcaseview#217]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I am using onTargetClick and onToolTipClick for custom logic like jumping pages, scrolling into view, etc.
However, it is AFAIK not possible to hook into when user taps on the background. It would be great to have this kind of functionality. For example could feature tour manually dismissed when tapped in background?

**Describe alternatives you've considered**
Feel free to change approach.

**Comment by vatsaltanna** [comment]
Hi @arndt-s , your requested feature has been taken care in PR #252 , and the changes will be available to use in next version release. Closing this for now feel free to reopen this for any other assistance.
