### ISSUE TITLE
Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null

### ISSUE THREAD

**Issue by AbdullahAli1993** [SimformSolutionsPvtLtd/flutter_showcaseview#228]
I always get these warnings and it is pretty annoying

/C:/dev/flutter/.pub-cache/hosted/pub.dartlang.org/showcaseview-1.1.5/lib/src/measure_size.dart:44:22: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/dev/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance!.addPostFrameCallback(postFrameCallback);
                     ^
/C:/dev/flutter/.pub-cache/hosted/pub.dartlang.org/showcaseview-1.1.5/lib/src/layout_overlays.dart:127:22: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/dev/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.addPostFrameCallback((_) => showOverlay());
                     ^
The cause is mentioned here 
https://stackoverflow.com/a/72229204/14564110

Thank you for your great work

**Comment by vatsaltanna** [comment]
Hi @AbdullahAli1993, This warning has been solved in the the PR #216 . Changes will be availbale in next release.

**Comment by vatsaltanna** [comment]
Hi @AbdullahAli1993, This warning has been solved in the the PR #216 . Changes will be availbale in next release.
