### ISSUE TITLE
1.1.6 scrolling behavior in PageView.

### ISSUE THREAD

**Issue by codyfilatov** [SimformSolutionsPvtLtd/flutter_showcaseview#235]
1.1.6 scrolling causing odd behavior in PageView.

- Set showcase view on an item inside of a PageView.
- When targeting items near the edge of the screen it attempts to scroll.
- Scroll bounces back and the target is in wrong location.

Can this new scrolling functionality be disabled? Occur on all devices in PageView.

**Comment by ITASerus** [comment]
same problem here
