### ISSUE TITLE
Add TextAlign attribute for description

### ISSUE THREAD

**Issue by duy-mai-otsv** [SimformSolutionsPvtLtd/flutter_showcaseview#253]
I have a question why don't you provide an alignment attribute for the description

And, if possible, can I support you do this thing?

**Comment by vatsaltanna** [comment]
Hi @duy-mai-otsv , we would love to have you as a contributor. we are open for any kind of contribution to this package. You can create a PR with the functionality you requested.

**Comment by Abu-muhab** [comment]
@vatsaltanna I have opened a PR relating to this issue. A review would be great
