### ISSUE TITLE
let user possibility to interact directly with target widget

### ISSUE THREAD

**Issue by Dekhnar** [SimformSolutionsPvtLtd/flutter_showcaseview#261]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
My targeted widget has two buttons, one for accepting the other for refusing. I would be nice, if you can propagate gesture event to the target children for letting the user ability to click on those buttons and managing the showcase flow manually?
 Currently onTap from TargetWidget handles the event and then stops propagating.

**Comment by Dekhnar** [comment]
I find a workaround and programmatically running my wanted action.

**Comment by DhavalRKansara** [comment]
@Dekhnar It will be great if you can share some information regarding the same feature you required in way of code, screenshots or workaround you have found.

**Comment by Dekhnar** [comment]
I used **onTargetClick** function exposed by **Showcase** to fired an event into my event bus, listen to this event and then execute my action.

**Comment by Dekhnar** [comment]
@DhavalRKansara I would be great if we can manually manage gesture. Maybe possible by letting us set null onTap, onLongPress, onDoubleTap there :
https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/blob/8af0bc1f3924b92e06275cff11c9dc79a49c37b4/lib/src/showcase.dart#L382

**Comment by DhavalRKansara** [comment]
@Dekhnar Sure, We will check on it from our end we will let you know if plan to make those changes...

**Comment by vatsaltanna** [comment]
Hi @Dekhnar , I tried to investigate your suggestion and I belive the current behaviour is implemented because usually the target widget has their own action(like screen change) which is not required to be performed while showcase of the application feature. And even if that is the necessory behaviour then user can use the different call back of gesture like onTap, onDoubleTap or onLongPress. Please let us know if there is any other usecase you require ?

**Comment by Dekhnar** [comment]
Hi @vatsaltanna, for example if you want to let the user swiping a card to the right, onTap, onDoubleTap, orLongPress will not be enought. By letting us setting behaviour on the focused area, we will be able to catch these king of gesture.

**Comment by vatsaltanna** [comment]
Got it, Thanks for the information. I will work on this feature soon. Thanks for reporting.
