### ISSUE TITLE
I'm wanting to use more my wheels are named

### ISSUE THREAD

**Issue by CadisRaziel** [SimformSolutionsPvtLtd/flutter_showcaseview#265]
From what I've seen so far, there's no way to use it with named routes?

look at my materialApp

  @override
  Widget build(BuildContext context) {
    final DependencyInjector dependencyInjector =
        AppModules.initDependencyInjector();
    return MaterialApp(
      debugShowCheckedModeBanner: false,
     
      title: 'AppTest',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),    
      initialRoute: "/splashPage",
      routes: RoutesName.routesName(dependencyInjector),
    );
  }

  @override
  Widget build(BuildContext context) {
    final DependencyInjector dependencyInjector =
        AppModules.initDependencyInjector();
    return MaterialApp(
      debugShowCheckedModeBanner: false,
     
      title: 'AppTeste',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
-----------------------------------------------------------------------------------
      home: Scaffold(
        body: ShowCaseWidget(         
          blurValue: 3,
          builder: Builder(builder: (context) => const MailPage()),
          autoPlayDelay: const Duration(seconds: 3),
        ),
      ),
-----------------------------------------------------------------------------------
      initialRoute: "/splashPage",
      routes: RoutesName.routesName(dependencyInjector),
    );
  }

my homepage is '/splashPage', in that case how could I do it?

**Comment by vatsaltanna** [comment]
Hi @CadisRaziel , you should wrap showcasewidget inside splash screen widget instead of home parameter of material app.

```

class SplashScreen extends StatelessWidget {
  const SplashScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ShowCaseWidget(
        blurValue: 3,
        builder: Builder(
          builder: (context) => const SplashScreenContent(),
        ),
        autoPlayDelay: const Duration(seconds: 3),
      ),
    );
  }
}
```

**Comment by CadisRaziel** [comment]
ok thanks @vatsaltanna

**Comment by vatsaltanna** [comment]
Closing this for now, feel free to reopen this issue  if you need any other assitance related to this.
