### ISSUE TITLE
A long description overflows

### ISSUE THREAD

**Issue by gitaaron** [SimformSolutionsPvtLtd/flutter_showcaseview#27]
Including a long description for the 'Showcase' widget makes the tooltip overflow to the right past the screen so that part of the tooltip is hidden.

Is there any recommendation on how to fix this?

Thanks!

**Comment by cgowthamanmca** [comment]
same problem please fix

**Comment by cgowthamanmca** [comment]
use new line "\n" this working fine

**Comment by gitaaron** [comment]
hey @cgowthamanmca  I added a PR to fix this - 

https://github.com/simformsolutions/flutter_showcaseview/pull/30

**Comment by cgowthamanmca** [comment]
@gitaaron Thanks working good

**Comment by gitaaron** [comment]
hi @cgowthamanmca - made a few more changes in a new local repo 

1. new showcase popup views (for cases where I want to display a message in the middle of a slideshow that is not tied to a UI component)
2. FIX: display popover above spotlight if there is more space above then below
3. implemenation for skipping proceeding slides (if user taps 'skip' button)

if these are of interest to you then lemme know and I'll submit a PR

**Comment by GrahamDi** [comment]
@gitaaron 
Hi, Has there been any further progress on this? I am keen to see the issue resolved and also for the three suggested new features. Good package :-)

**Comment by vipulasri** [comment]
@BirjuVachhani can you check this issue as well, happening to me as well.
