### ISSUE TITLE
showArrow not working inside withWidget;

### ISSUE THREAD

**Issue by ShakeelBeyondvision** [SimformSolutionsPvtLtd/flutter_showcaseview#271]
First, I am very thankful to the developer who created this amazing widget. I am trying to add skip and next buttons inside the tooltip box but there isn't a way to implement it. Then I got a method to add skip and next button using `Showcase.withWidget` but by using this method `showArrow` is not working. How can I add an arrow on my tooltip? Here is my code,

` return Showcase.withWidget(
    key: key,
    container: Container(
      padding: const EdgeInsets.symmetric(
        vertical: 20,
        horizontal: 25,
      ),
      width: MediaQuery.of(context).size.width - 30,
      decoration: BoxDecoration(
        color: whiteColor,
        borderRadius: BorderRadius.circular(24),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          if (title != null) ...{
            Text(
              title,
              style: const TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.w600,
                color: Colors.black,
                height: 2,
              ),
            ),
          },
          if (description != null) ...{
            Text(
              description,
              style: const TextStyle(
                fontSize: 12,
                fontWeight: FontWeight.w400,
                color: Colors.black87,
                height: 1.5,
              ),
            ),
          },
          Container(
            margin: const EdgeInsets.only(
              top: 15,
            ),
            child: Row(
              children: [
                InkWell(
                  onTap: () {
                    onSkip();
                    ShowCaseWidget.of(context).dismiss();
                  },
                  child: const Text(
                    'Skip',
                    style: TextStyle(
                      fontSize: 16,
                      fontWeight: FontWeight.w600,
                      color: Color.fromRGBO(179, 179, 179, 1),
                    ),
                  ),
                ),
                const Spacer(),
                InkWell(
                  onTap: () {
                    onNext();
                    ShowCaseWidget.of(context).next();
                  },
                  child: Row(
                    children: [
                      Text(
                        'Next',
                        style: TextStyle(
                          fontSize: 16,
                          fontWeight: FontWeight.w600,
                          color: themeColorBG,
                        ),
                      ),
                      Icon(
                        Icons.keyboard_arrow_right_rounded,
                        size: 25,
                        color: themeColorBG,
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    ),
    height: MediaQuery.of(context).size.height / 2,
    width: double.infinity,
    child: child,
  );`

![Screenshot_1663249083](https://user-images.githubusercontent.com/31476882/190419020-0c98046e-e270-4301-8c84-9e7c0d76edf5.png)

**Comment by HappyMakadiyaS** [comment]
Hi @ShakeelBeyondvision, For now we are not looking for it. Though withWidget is intent to create fully customised tooltip. So you have to add arrow by your own.
