### ISSUE TITLE
Detect user click at any place other than tool tip or target

### ISSUE THREAD

**Issue by cool2apps** [SimformSolutionsPvtLtd/flutter_showcaseview#272]
**Is your feature request related to a problem? Please describe.**
It is not possible to detect if user clicked at any place (other than tool tip or target) on screen to skip to next showcase. Wrapping showcase widget with GestureDetector does not help.

**Describe the solution you'd like**
There are 2 handlers: onTargetClick and onToolTipClick to detect clicks on target and tool tip. It would be better if there is 3rd handler, for example onCllck or orAnywhereClick to detect clicks other than target and tool tip.

**Describe alternatives you've considered**
none.

**Additional context**
none.

**Comment by ManfredStoiber** [comment]
I also wondered if there is any possibility for that. For my case, I just needed to disable clicking elsewhere to "enforce" the user to go through the app introduction. 

As a workaround, I set `autoPlay` and `enableAutoPlayLock` to `true` and `autoPlayDelay` to `Duration(days: 365)`, maybe this could help you
