### ISSUE TITLE
[Bug] ShowcaseWidget in body of Scaffold with AppBar displays showcase at wrong offset

### ISSUE THREAD

**Issue by SeriousMonk** [SimformSolutionsPvtLtd/flutter_showcaseview#274]
I have a Scaffold that serves as main page and contains an Appbar. All other pages are displayed as body of this scaffold. Some of these subpages have a ShowcaseWidget. The structure is as follows:
```dart
Scaffold(
  appBar: AppBar(
    ...
  ),
  body: ShowcaseWidget(
    builder: Builder(
      builder: (context){
        return Scaffold(
          floatingActionButton: Showcase(
            ...
          )
        );
      }
    )
  )
);
```

With this code the Showcase is placed under the actual widget of the exact height of the app bar (this happens also for widgets in the body of the nested scaffold, not only the FloatingActionButton). 

![Screenshot 2022-10-05 113824](https://user-images.githubusercontent.com/26068515/194030394-8534faf6-7bb1-4329-860a-ccb862239036.png)

If however I set the ```extendBodyBehindAppBar``` like follows, everything works as expected: 
```dart
Scaffold(
  extendBodyBehindAppBar: true,
  appBar: AppBar(
    ...
  ),
  body: ShowcaseWidget(
    builder: Builder(
      builder: (context){
        return Scaffold(
          floatingActionButton: Showcase(
            ...
          )
        );
      }
    )
  )
);
```

**Comment by vatsaltanna** [comment]
Hi @SeriousMonk , floatingActionButton is an animated widget and so please add delay before you start the showcase view  so that showcase view widget know the final position of floatingActionButton after the animation.

**Comment by SeriousMonk** [comment]
As stated in the issue, this behavior happens also with widgets other than FloatingActionButton, such as ListTile. The problem, I believe, is a bug in the vertical offset calculation when there are nested Scaffold, where the external Scaffold has an AppBar.

**Comment by dhvanit-v-simformsolutions** [comment]
Hi @SeriousMonk , I have tried to replicate mentioned issue, yet I could't replicate that one. So, could you please provide code snippet with showcaseview version and running device in which you are facing mentioned issue ?
