### ISSUE TITLE
Showcase highlight not correctly highlighting child widget on smartphone

### ISSUE THREAD

**Issue by keitheyre** [SimformSolutionsPvtLtd/flutter_showcaseview#275]
**Describe the bug**
![image](https://user-images.githubusercontent.com/27727833/194294202-52972bda-dbb4-41ee-99ff-86ecb4242eec.png)

**To Reproduce**
1. Wrap FAB in Showcase widget
2. Open on smartphone (Android A7 smartphone)
3. See error (View attached image above)

**Expected behavior**
Highlight FloatingActionbutton

**Screenshots**
![image](https://user-images.githubusercontent.com/27727833/194294376-663d21f4-c628-40a2-8205-7c24797df3e4.png)

**Smartphone (please complete the following information):**
 - Device: Samsung A7
 - OS: Android 8.1
 - Browser N/A

**Additional context**
Seems to work perfectly with no overlayPadding required, but for smartphone, it is WAY off.

**Comment by cool2apps** [comment]
I have the same problem. This problem exits on non FAB widgets too. Any solution?

**Comment by keitheyre** [comment]
> I have the same problem. This problem exits on non FAB widgets too. Any solution?

I haven’t found a solution yet. Waiting for tan to see this issue. Hopefully sooner rather than later

**Comment by cool2apps** [comment]
Sometimes this workaround solves the problem, but not every time.

use this
```
      await Future.delayed(const Duration(milliseconds: 500));
      ShowCaseWidget.of(context).startShowCase(Shared.globalKeys);
```
instead of this
```
      WidgetsBinding.instance.addPostFrameCallback((_) => ShowCaseWidget.of(context).startShowCase(Shared.globalKeys));
```

**Comment by cool2apps** [comment]
When next release will be published?

**Comment by naitbrahim** [comment]
> Hello Guys, This issue has been solved and it will be available with next release.

Can you please an estimate date for the next release ? thank you very much.

**Comment by vatsaltanna** [comment]
Please expect a new release withing 24 to 48 hours.

**Comment by vatsaltanna** [comment]
Please note that if you are wrapping showcase view to an animated widget then you need to add some delay before it starts. for example in the first case of the issue it's FAB which has it's own animation. so start a showcase with some delay until it gets to it's actual position.

**Comment by vatsaltanna** [comment]
Hi @cool2apps , if you are using FAB and it's the first one to get highlighted then I think below code should work.
```
    WidgetsBinding.instance.addPostFrameCallback((_) async {
      await Future.delayed(const Duration(milliseconds: 500));
      ShowCaseWidget.of(context).startShowCase(globalKeys);
    });
```

**Comment by cool2apps** [comment]
> Hi @cool2apps , if you are using FAB and it's the first one to get highlighted then I think below code should work.
> 
> ```
>     WidgetsBinding.instance.addPostFrameCallback((_) async {
>       await Future.delayed(const Duration(milliseconds: 500));
>       ShowCaseWidget.of(context).startShowCase(globalKeys);
>     });
> ```

link gave me ```Do not use BuildContexts across async gaps.``` warning but it looks like working. I don't know if this warning will cause a problem or not.

**Comment by naitbrahim** [comment]
Thank you @vatsaltanna it's working like a charm now ;)
it's a time saving, thanks again
