### ISSUE TITLE
Example how to use ShowCase inside a widget

### ISSUE THREAD

**Issue by DiegoVega19** [SimformSolutionsPvtLtd/flutter_showcaseview#277]
i'm new to flutter and using the package, sorry for my question, but how can i use showcase inside a widget, i.e. i have my homepage, but inside my homepage i have an appbar widget, so i want to show the showcase inside an action of my appbar widget. can you provide me an example? all the examples using showcase inside the same widget.

**Comment by vatsaltanna** [comment]
Hi @DiegoVega19, It's very simple to use. please refer [example project](https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/tree/master/example)/ [Readme](https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview) from the repo.
