### ISSUE TITLE
Provide a callback to return the tooltip position and the size of showcase item

### ISSUE THREAD

**Issue by anderscheow** [SimformSolutionsPvtLtd/flutter_showcaseview#279]
**Is your feature request related to a problem? Please describe.**
For tooltip position:
Currently my tooltip including arrow to highlighted the showcase item. But somehow in some situation the tooltip showing below the showcase item, and the arrow is pointing downward.

For tooltip size:
I placed two buttons on the tooltip which align to most right. When the showcase item is too small and positioned on left, the buttons seems a bit off when aligned to most right. Currently there's no way to know where I want to position the buttons.

**Describe the solution you'd like**
1. Provide a callback to return the tooltip position so that I able to rotate or flip the arrow
2. Size of the showcase item so that can provide more customisation when creating custom tooltip

**Comment by vatsaltanna** [comment]
Hi @anderscheow , Could you please share the screenshot or video of the issue you have faced ? Although, we have fixed some positioning issue and it will be available in next release.

**Comment by anderscheow** [comment]
![CleanShot 2022-10-28 at 08 27 53](https://user-images.githubusercontent.com/11788504/198422047-2c9bb892-294b-4f13-b033-ceff56100be0.jpg)

Firstly, I would like to position the showcase content to the top, but currently I cannot achieve that.

Secondly, I would like to know the size of the highlighted showcase item, so that I can wrap the content in a Container with a same width as the highlighted showcase item.

**Comment by dhvanit-v-simformsolutions** [comment]
@anderscheow For your first concern you can use the latest version of showcaseview, where you can find `tooltipPosition` in the `Showcase` class or the `Showcase.withWidget` constructor. For the second concern, we will inform you. Thank you!!

**Comment by DhvanitVaghani** [comment]
> ![CleanShot 2022-10-28 at 08 27 53](https://user-images.githubusercontent.com/11788504/198422047-2c9bb892-294b-4f13-b033-ceff56100be0.jpg)
> 
> Firstly, I would like to position the showcase content to the top, but currently I cannot achieve that.
> 
> Secondly, I would like to know the size of the highlighted showcase item, so that I can wrap the content in a Container with a same width as the highlighted showcase item.


@anderscheow For getting the size of highlighted showcase item, you can get it with the provided key of that item. For instance, `key.currentContext.size`. Make sure whenever you try to get size with a key wrap that code in `WidgetsBinding.instance.addPostFrameCallback((timeStamp) {}` otherwise you will get an error.  I am closing this issue. Feel free to reopen it if you encounter any concerns. Thank you!!
