### ISSUE TITLE
request enable param :  disableDefaultTargetGestures 

### ISSUE THREAD

**Issue by bhargav6744** [SimformSolutionsPvtLtd/flutter_showcaseview#280]
Enable disableDefaultTargetGestures parameter in Showcase.withWidget or ShowCaseWidget

**Comment by vatsaltanna** [comment]
Hi @bhargav6744 , Can you please elaborate your request with more details or example?

**Comment by HappyMakadiyaS** [comment]
Hi @bhargav6744,
By default target gesture is already enabled if you want to disable default gestures of target widget then you can use this `disableDefaultTargetGestures` param.

Closing this issue. Feel free to reopen this if this solution doesn't work for you.
