### ISSUE TITLE
Unhandled Exception: Exception: Please provide ShowCaseView context

### ISSUE THREAD

**Issue by pritamkarmakar** [SimformSolutionsPvtLtd/flutter_showcaseview#289]
**Describe the bug**
If I try to start the showcase from init getting this error "Unhandled Exception: Exception: Please provide ShowCaseView context". But if I start from a button click it works fine.

**To Reproduce**
Here is how the overall Stateful widget looks like -

```
 final _key1 = GlobalKey();
@override
  void initState() {
    super.initState();
    _viewModel.getActiveMemberships().then((value) {
      WidgetsBinding.instance.addPostFrameCallback((_) async {
        ShowCaseWidget.of(context).startShowCase([_key1]);
      });
    });
  }

@override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider<ManageMembershipScreenViewModel>.value(
      value: _viewModel,
      child: Consumer<ManageMembershipScreenViewModel>(
        builder: (context, model, child) => Scaffold(
          appBar: AppBar(...),
          body: ShowCaseWidget(
            builder: Builder(
              builder: (context) => Stack(children: [
..........
```

I have wrapped one UI element within `Showcase` inside the `Scaffold`

**Comment by vatsaltanna-simformsolutions** [comment]
Hi @pritamkarmakar , please add `ShowCaseWidget` in the parent widget of your current code or use `startShowCase` function after the use of `ShowCaseWidget` in this case inside `Builder` widget as `ShowCaseWidget` is a inherited widget and it requires the context of widget which has the  ShowCaseWidget.

**Comment by pritamkarmakar** [comment]
Thank you for looking into it, worked fine with proper context as you mentioned.
