### ISSUE TITLE
Description width calculation does not account for text with multiple lines i.e "\n"

### ISSUE THREAD

**Issue by Abu-muhab** [SimformSolutionsPvtLtd/flutter_showcaseview#290]
**Describe the bug**
The width of the description text does't get calculated properly when the new line character (\n) is contained in the text. This causes the showcase to either take up much lesser(making the text very condensed) or more space than required 

**Current Implementation**
`Size _textSize(String text, TextStyle style) {
    final textPainter = (TextPainter(
            text: TextSpan(text: text, style: style),
            maxLines: 1,
            textScaleFactor: MediaQuery.of(context).textScaleFactor,
            textDirection: TextDirection.ltr)
          ..layout())
        .size;
    return textPainter;
  }`

**Proposed solution**
` Size _textSize(String text, TextStyle style) {
    final String longestLine = text.split('\n').reduce(
          (String longest, String current) =>
              longest.length > current.length ? longest : current,
        );
    final textPainter = (TextPainter(
            text: TextSpan(text: longestLine, style: style),
            maxLines: 1,
            textScaleFactor: MediaQuery.of(context).textScaleFactor,
            textDirection: TextDirection.ltr)
          ..layout())
        .size;
    return textPainter;
  }
}`

**Comment by HappyMakadiyaS** [comment]
Hi @Abu-muhab, The bug you have describe is not reproducing in latest master channel.
Closing this issue. Feel free to reopen this if you face same issue.
