### ISSUE TITLE
How can i make sure that the overlay stays behind a bottom sheet?

### ISSUE THREAD

**Issue by desmeit** [SimformSolutionsPvtLtd/flutter_showcaseview#303]
Is it possible to ensure that the overlay only overlays a specific widget? In my case a bottom sheet opens after startup.

Thanks

**Comment by nzackoya** [comment]
Why is this closed? I believe this should have an attention. flutter_showcaseview is an overlay, which makes some flows really problematic to handle

**Comment by pavan-rheo** [comment]
@nzackoya any update you have on this?
