### ISSUE TITLE
Exception: Please provide ShowCaseView context

### ISSUE THREAD

**Issue by vivekprasad99** [SimformSolutionsPvtLtd/flutter_showcaseview#304]
**Describe the bug**
I am getting this issue when using showCaseView
Exception: Please provide ShowCaseView context

**Expected behavior**

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Please provide ShowCaseView context
E/flutter (29920): #0      ShowCaseWidget.of (package:showcaseview/src/showcase_widget.dart:110:7)
E/flutter (29920): #1      _CategoryListingWidgetState.initState.<anonymous closure> (package:awign/workforce/onboarding/presentation/feature/category_listing/widget/category_listing_widget.dart:57:24)

**Comment by HappyMakadiyaS** [comment]
hi @vivekprasad99 
Might you have used ShowCaseWidget.of(context) before `ShowCaseWidget` render into widget tree.

**Comment by HappyMakadiyaS** [comment]
https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/issues/289#issuecomment-1293385374
