### ISSUE TITLE
Custom position of tooltip

### ISSUE THREAD

**Issue by rmahmadkhan** [SimformSolutionsPvtLtd/flutter_showcaseview#312]
Hello, I want to customize the position of my custom tooltip when using `Showcase.withWidget()`.

Currently, my widget takes position automatically as follows. I want to place it to the center right of the target. Any tips?

<img width="1552" alt="Screenshot 2022-12-07 at 9 11 50 AM" src="https://user-images.githubusercontent.com/46877003/206087179-b51f6f3c-c711-492b-84c0-c8da694ed4dc.png">

**Comment by vatsaltanna** [comment]
Hi @rmahmadkhan , Unfortunately right now we have only vertical positions available for tooltip. you can use `tooltipPosition: TooltipPosition.top` or `tooltipPosition: TooltipPosition.down` for manual positioning.

**Comment by ziqq** [comment]
> Hi @rmahmadkhan , Unfortunately right now we have only vertical positions available for tooltip. you can use `tooltipPosition: TooltipPosition.top` or `tooltipPosition: TooltipPosition.down` for manual positioning.

It won't fit. I want to full customize the position.

**Comment by SPSpisoft** [comment]
I'm having the same problem, we have a vertical widget group that spans almost the entire height of the device, so we need to display the widget on the correct side (eg left or right). TooltipPosition.top /TooltipPosition.down is not currect.

**Comment by liqvip** [comment]
I ran into the same problem, is there any progress on this feature

**Comment by aditya-css** [comment]
Closing this issue as it is duplicate of #54.
