### ISSUE TITLE
titleAlignment parameter seems to be bugged

### ISSUE THREAD

**Issue by Kolompos** [SimformSolutionsPvtLtd/flutter_showcaseview#315]
**Describe the bug**
Showcase's titleAlignment parameter seems to be bugged. TextAlign.center is effective only if the text to be displayed is longer than what fits into a single line.

**To Reproduce**
1. Set up a Showcase()
2. For the title: set a text that is short
3. For the titleAlignment: set TextAlign.center
4. See the alignment
5. Now set the title for someting longer that one line.
6. See that the alignmet is correct.

**Expected behavior**
I expected it to work for even a single letter.

**Screenshots**
![two](https://user-images.githubusercontent.com/27746221/208271347-4090f879-58ca-41e5-a0c3-af5e6f74efb0.PNG)
![one](https://user-images.githubusercontent.com/27746221/208271348-3f5936fb-38cc-438d-b5e0-1aa3550bdb4e.PNG)

**Desktop
 (please complete the following information):**
 - OS: Android and Web

**Comment by ujas-m-simformsolutions** [comment]
@Kolompos The `titleAlignment` will not center the text widget rather it will align in side the whatever space it has taken.
In second screenshot there is much more space is available so it is not align the text. The same behavior will happen for normal Text widget if you use `textAlign` in it. 

So for this you can use `Showcase.withWidget()` constructor and pass your custom widget and for your title widget just wrap it with `Center` widget.

**Comment by Tokenizer94** [comment]
> @Kolompos The `titleAlignment` will not center the text widget rather it will align in side the whatever space it has taken. In second screenshot there is much more space is available so it is not align the text. The same behavior will happen for normal Text widget if you use `textAlign` in it.
> 
> So for this you can use `Showcase.withWidget()` constructor and pass your custom widget and for your title widget just wrap it with `Center` widget.

Then why there is a titleAlignment and titleTextDirection? Both of these are not working. Please fix it.
