### ISSUE TITLE
Showcase Boolean

### ISSUE THREAD

**Issue by errajibadr** [SimformSolutionsPvtLtd/flutter_showcaseview#318]
Hello,

is it possible to add a  feature:
a boolean to enable (or no)t the showcase since most of the times we only want it to play the first time.

thus avoiding a lot of boilerplate code with:  
`` if(showcase) Showcase(child:Screen) else Screen

or is there a better practice for that? 

Thankyou,

**Comment by BirjuVachhani** [comment]
Looks good to me! Let's see what others think!

**Comment by ujas-m-simformsolutions** [comment]
This is fine. We can provide this feature.
