### ISSUE TITLE
Can you possible to set showArrow in custom widget?

### ISSUE THREAD

**Issue by Govindbetterlives** [SimformSolutionsPvtLtd/flutter_showcaseview#323]
Hi, How can I set showArrow in the custom widget? Any idea for this?

**Comment by DhvanitVaghani** [comment]
Hi, @Govindbetterlives. You can make a custom widget for the same and pass it in the `Showcase.withWidget()` constructor. Hope this makes sense, closing this issue for now. If you find any issues, feel free to reopen it. Thanks!!
