### ISSUE TITLE
Exception: Please provide ShowCaseView context

### ISSUE THREAD

**Issue by hgtucel** [SimformSolutionsPvtLtd/flutter_showcaseview#327]
It gives Exception: Please provide ShowCaseView context warning when ShowCaseWidget startShowCase is called in initState method while starting the page.

`@override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback(
        (_) => ShowCaseWidget.of(context).startShowCase([_one, _two]));
  }`
  
Warning given
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY 
The following _Exception was thrown during a scheduler callback:
Exception: Please provide ShowCaseView context
When the exception was thrown, this was the stack:

**I can show it in button's onPress method but in initState it gives this error.**

Flutter Version: 3.7.0
flutter_showcaseview: ^2.0.9

Platforms tested and bugs: Web, iOS, Android

**Comment by faiyaz-shaikh** [comment]
Hi, @hgtucel I am not able to reproduce it, Can you please share the reproducible code so it will be helpful? Also, you can check similar issues we have closed [here](https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/issues?q=is%3Aissue+Please+provide+ShowCaseView+context+is%3Aclosed) If You might have used incorrectly. Thanks.

**Comment by faiyaz-shaikh** [comment]
Hi @ziqq I tried to reproduce it from the code which you have given. It is working fine I am not getting any error.

**Comment by ziqq** [comment]
> Hi @ziqq I tried to reproduce it from the code which you have given. It is working fine I am not getting any error.

It's will be fixed [here](https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/issues/334#event-8582658769)

**Comment by ujas-m-simformsolutions** [comment]
Duplicate of #324. Please use solution from [this](https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/issues/324#issuecomment-1376808799) comment.
