### ISSUE TITLE
showcase position rarely looks wrong

### ISSUE THREAD

**Issue by tyypgzl** [SimformSolutionsPvtLtd/flutter_showcaseview#329]
**Describe the bug**
We do not always catch this error. It rarely does. I have come across this in the applications I have developed before.
I'm uploading the wrong screenshot and what we expect.

Error                                                                                 | Expect                         
:---------------------------------------------------:|:-------------------------------------------------------------------------:
![error](https://user-images.githubusercontent.com/86917901/215467216-51ec12b5-a2f0-48c3-ba68-c6b614bd8134.jpeg) | ![expect](https://user-images.githubusercontent.com/86917901/215467136-16cac377-1406-4ca7-a0a1-e24fe82f2d31.png)

```dart
ShowCaseWidget(
          onFinish: () => context.read<CalendarBloc>().add(
                ShowCaseFinished(),
              ),
          builder: Builder(
            builder: (context) {
              return ResponsiveSizer(
                builder: (context, orientation, screenType) {
                  return MaterialApp.router(
                    debugShowCheckedModeBanner: false,
                    supportedLocales: AppLocalizations.supportedLocales,
                    locale: appointmentState.locale,
                    localizationsDelegates: const [
                      SfGlobalLocalizations.delegate,
                      AppLocalizations.delegate,
                      GlobalMaterialLocalizations.delegate,
                      GlobalCupertinoLocalizations.delegate,
                      GlobalWidgetsLocalizations.delegate,
                      DefaultCupertinoLocalizations.delegate,
                    ],
                    onGenerateTitle: (context) => context.l10n.appTitle,
                    routerDelegate: _appRouter.delegate(
                      navigatorObservers: () => [
                        AppRouterObserver(),
                      ],
                    ),
                    routeInformationParser: _appRouter.defaultRouteParser(),
                    themeMode: appointmentState.themeMode,
                    theme: lightTheme,
                    darkTheme: darkTheme,
                  );
                },
              );
            },
          ),
        )
```

- The startShowCase function is in initState.

```dart
  @override
  void initState() {
 ShowCaseWidget.of(context).startShowCase(
            [
              changeCalenderViewTypeKey,
              shareKey,
              autoConfirmationKey,
              rsvpSettingsKey
            ],
          );
    super.initState();
  }
```
- I am using the extension for the showcase widget.

```dart
  Widget addShowCase({
    required String description,
    required GlobalKey<State<StatefulWidget>> key,
    EdgeInsets? targetPadding,
    required ColorScheme colorScheme,
  }) =>
      Showcase(
        descTextStyle: const TextStyle(
          fontSize: 16,
          letterSpacing: 0,
        ),
        description: description,
        disableMovingAnimation: true,
        movingAnimationDuration: const Duration(seconds: 1),
        scaleAnimationDuration: const Duration(milliseconds: 200),
        targetBorderRadius: const BorderRadius.all(
          Radius.circular(8),
        ),
        tooltipBorderRadius: const BorderRadius.all(
          Radius.circular(8),
        ),
        targetPadding: targetPadding ?? const EdgeInsets.all(4),
        tooltipPadding: const EdgeInsets.all(12),
        textColor: colorScheme.onBackground,
        tooltipBackgroundColor: colorScheme.background,
        key: key,
        child: this,
      );
```

**Comment by DhvanitVaghani** [comment]
Hi, @tyypgzl. I have tried to replicate the issue but could not replicate it. Are you still facing this issue?

**Comment by rasyeda** [comment]
Same issue here, rarely happens on iOS devices.

**Comment by tyypgzl** [comment]
> 

As I mentioned, it doesn't always happen. We encountered this error 2 times in 3 months.

**Comment by FriendlyNeighbor** [comment]
You shouldn't actually use

```
WidgetsBinding.instance.addPostFrameCallback((_) =>
  ShowCaseWidget.of(context).startShowCase([key])
);
```

but instead use

```
Future.delayed(const Duration(milliseconds: 500), () async {
        ShowCaseWidget.of(context).startShowCase(
          [key],
        );
      });
```

on some devices, the showcaseview shows correctly in place, on some devices, it doesn't just like yours. This was really messing up our release. Unfortunately there are no other libraries that implements similar to this so I gotta figure out a solution.

This worked perfectly across different devices (as I am testing on different actual device and emulators).

**Comment by Gidzkid** [comment]
Same issue here when i trying to use responsive_framework  lib to set my app max width.

**Comment by basunia** [comment]
> You shouldn't actually use
> 
> ```
> WidgetsBinding.instance.addPostFrameCallback((_) =>
>   ShowCaseWidget.of(context).startShowCase([key])
> );
> ```
> 
> but instead use
> 
> ```
> Future.delayed(const Duration(milliseconds: 500), () async {
>         ShowCaseWidget.of(context).startShowCase(
>           [key],
>         );
>       });
> ```
> 
> on some devices, the showcaseview shows correctly in place, on some devices, it doesn't just like yours. This was really messing up our release. Unfortunately there are no other libraries that implements similar to this so I gotta figure out a solution.
> 
> This worked perfectly across different devices (as I am testing on different actual device and emulators).

It works like charm! Thanks

**Comment by vatsaltanna** [comment]
We have pinned issue #378 to help others in this situation. As adding delay solves this issue, I am assuming it is solved and closing this issue for now. Feel free to reopen this issue if it still persists.
