### ISSUE TITLE
How to control widget orientation

### ISSUE THREAD

**Issue by cwdsgi** [SimformSolutionsPvtLtd/flutter_showcaseview#331]
I want the widget below the highlight

**Comment by DhvanitVaghani** [comment]
Hi, @cwdsgi. For showing the widget below highlight you need to pass `tooltipPosition` in `Showcase` or `Showcase.withWidget`.

**Comment by cwdsgi** [comment]
But showcaseview didn't provide tooltipPosition

**Comment by DhvanitVaghani** [comment]
@cwdsgi, Seems like something is misunderstood here. `Showcase` does have a `tooltipPosition` parameter. Also, `Showcase` is responsible for highlighting your widget and the tooltip over that highlighted widget. The same behaviour `Showcase.withWidget` also has. Moreover, you can see an example from the repo where you can take a reference.  I hope this will help you. Thanks!!

**Comment by FabioSpano** [comment]
@DhvanitVaghani 

In the current version there isn't a `tooltipPosition` parameter. Which parameter are you referring to?

**Comment by DhvanitVaghani** [comment]
@cwdsgi  @FabioSpano Yes, apologize for the inconvenience. This feature will be available in the next release. Thank you for your patience

**Comment by vatsaltanna** [comment]
New version of `showcaseview: ^2.0.1` has been released. please use that version for this feature.
