### ISSUE TITLE
ShowCaseWidget doesn't let work Flutter Inspector - Makes Screen Grey

### ISSUE THREAD

**Issue by HornyPony** [SimformSolutionsPvtLtd/flutter_showcaseview#335]
It happens when I use auto_route in my app

<img width="327" alt="image" src="https://user-images.githubusercontent.com/67595447/216824408-a4e8e768-1551-45be-9d0d-cb2bc12b440e.png">

**Comment by DhvanitVaghani** [comment]
Hi, @HornyPony Could you please share code snippets here in which the issue occurred? Thanks!!

**Comment by etienn01** [comment]
Facing the same issue. Anytime you have a `Showcase` in the widget tree, enabling Flutter's debug paint shows a gray overlay that makes the feature kind of unusable.

| Without `Showcase` | With `Showcase` |
| - | - |
| ![image](https://user-images.githubusercontent.com/1763929/219615494-eedf4645-d420-4b48-8ba5-f5187b60d519.png) | ![image](https://user-images.githubusercontent.com/1763929/219615666-d7635af0-2a08-41c9-9ca1-4fea7d37b232.png) |
