### ISSUE TITLE
showcase to display behind a modal bottom sheet

### ISSUE THREAD

**Issue by holotomy** [SimformSolutionsPvtLtd/flutter_showcaseview#339]
How to make showcase view display behind a modal / bottom sheet? I have a bottom sheet to display and showcase view at home page at the same time . Thanks

**Comment by DhvanitVaghani** [comment]
Hi, @holotomy. Right now, we do not have any approach to satisfying your use case.  Yet, if you wish you can try this use case at your end and you can create PR for same as well. Thanks !
