### ISSUE TITLE
Confused in regards to onTargetClick and disposeOnTap

### ISSUE THREAD

**Issue by nicolasvahidzein** [SimformSolutionsPvtLtd/flutter_showcaseview#345]
Hello there,

I am confused about how these 2 work.

I need to detect when the showcase is disposed/dismissed. I enabled disposeOnTap to TRUE but i have no way of detecting that action and thus i cannot process that in my app.

I need to be able to show it again later when it is disposed as opposed to clicked on target.

This brings be to onTargetClick: it is not working consistently, when i press on the container it only clicks if i click in the bottom right corner.

I am utterly confused. Your help would be very much appreciated.

**Comment by ujas-m-simformsolutions** [comment]
Hey @nicolasvahidzein, If you want call-back when showcase is dismissed then you can use `onComplete` handler available in the `ShowCaseWidget` which gets called every time showcase gets dismissed. It also provides index and key so you can compare it to check which showcase got dismissed.

```
ShowCaseWidget(
          onComplete: (index, key) {
                   // Do anything
          },
)
```

**Comment by ujas-m-simformsolutions** [comment]
If this doesn't resolve your issue then feel free to reopen this issue.

**Comment by FriendlyNeighbor** [comment]
You named the parameter `key` but it doesn't actually catch the key you initialized in ```
ShowCaseWidget.of(context).startShowCase(
          [someKey],
        );
```

not actually the solution.
