### ISSUE TITLE
Reload current showcase

### ISSUE THREAD

**Issue by thanhnd10kn** [SimformSolutionsPvtLtd/flutter_showcaseview#365]
**Is your feature request related to a problem? Please describe.**
I have issue when when call API. Some widgets need data to display, but when onStart is called, the API has not finished loading

**Describe the solution you'd like**
I want a func to reload showcase when get data finished!. Thankyou!

**Comment by vatsaltanna** [comment]
You can call `onStart` whenever it is required. So in your case, you can use `onStart` after you receive your API data. The onStart` function is used to start the showcaseview, so it is not required to be used only when the widget loads; you can use it anywhere in the scope.

Closing this issue for now feel free to reopen if this answers is not helpfull or if you require any additional information.
