### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by jazzbpn** [SimformSolutionsPvtLtd/flutter_showcaseview#366]
<img width="503" alt="Screenshot 2023-03-28 at 12 49 25" src="https://user-images.githubusercontent.com/11361035/228155538-b0c8d828-54b1-4d83-8144-3749889b4d0c.png">

**Comment by DhvanitVaghani** [comment]
Hi @jazzbpn. Could you please confirm that this error is not reproducing from firebase crashlytics? If not, then please share code snippet where you are facing issue.

**Comment by gorkemalgan** [comment]
I am getting the same Fatal Exception: "Null check operator used on a null value. I am using version 2.0.2. Stack logs are as follows:

Fatal Exception: FlutterError
0  ???                            0x0 (null).#0      State.context (package:flutter/src/widgets/framework.dart:954:20)
0  ???                            0x0 (null).#1      _ShowcaseState.showCaseWidgetState (package:showcaseview/src/showcase.dart:345:68)
0  ???                            0x0 (null).#2      _ShowcaseState._nextIfAny (package:showcaseview/src/showcase.dart:426:5)

**Comment by gorkemalgan** [comment]
Another error similar to the first comment is also as follows:

0  ???                            0x0 (null).#0      State.setState (package:flutter/src/widgets/framework.dart:1153:13)
1  ???                            0x0 (null).#1      _ShowcaseState._reverseAnimateTooltip (package:showcaseview/src/showcase.dart:450:5)
2  ???                            0x0 (null).#2      _ShowcaseState._nextIfAny (package:showcaseview/src/showcase.dart:425:11)
3  ???                            0x0 (null).#3      _ShowcaseState._nextIfAny (package:showcaseview/src/showcase.dart:416:3)
4  ???                            0x0 (null).#4      _ShowcaseState._getOnTargetTap (package:showcaseview/src/showcase.dart:435:44)
5  ???                            0x0 (null).#5      _ShowcaseState._getOnTargetTap (package:showcaseview/src/showcase.dart:429:3)

**Comment by ujas-m-simformsolutions** [comment]
@jazzbpn @gorkemalgan please your share your implementation so that we can find the issue.

**Comment by jazzbpn** [comment]
<img width="1168" alt="Screenshot 2023-11-18 at 16 14 13" src="https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/assets/11361035/0dd85dc2-2502-4077-b69f-1bf9ac3c282b">

<img width="1141" alt="Screenshot 2023-11-18 at 16 18 36" src="https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/assets/11361035/ef738d36-3374-4178-b00f-1fd92c9052d5">
<img width="1160" alt="Screenshot 2023-11-18 at 16 15 56" src="https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/assets/11361035/1e4e3753-f3b3-4642-aa1e-a1a346b69565">
