### ISSUE TITLE
The target element is not focused properly

### ISSUE THREAD

**Issue by vatsa1101** [SimformSolutionsPvtLtd/flutter_showcaseview#367]
The target element is not focused properly for every showcase. The target element is always getting cropped from top with same height in all showcases.

![bug image](https://user-images.githubusercontent.com/71505416/228528508-688051ae-8f1c-4f52-8ba0-e274c128c20c.jpeg)

 - Device: iPhone 8
 - OS: iOS 16.3.1

**Comment by Fraa-124** [comment]
This is also happening to me. so weird

**Comment by Ujas-Majithiya** [comment]
From looks of it, the bottom navigation bar is being animated there. So when showcaseview tries to calculate position it get position when navbar is still in transition. Can you try putting some delay before you start showcase

**Comment by vatsaltanna** [comment]
@Eashubh128 Please apply the solution from this problem. #378 

Closing this issue for now, feel free to reopen it if the issue still persists.

**Comment by SeCo89** [comment]
Hi there, I've got the same problem having a bottom navbar. In my case no position is calculated correctly. Delaying is not working neither. I use responsive framework (https://pub.dev/packages/responsive_framework)in my app, is it possible that the Scaling is the problem in calculating the position?

**Comment by donvie** [comment]
Did you solve the problem? It happens to me also.

**Comment by SeCo89** [comment]
> Did you solve the problem? It happens to me also.

Unfortunately not. It's not possible for me to use this package this way.

**Comment by jaiminrana05** [comment]
Because the responsive framework internally modifies the mediaquery data, the package receives the incorrect screen height and width. As a result, for the time being, this package is incompatible with the responsive framework.

**Comment by chihuy105** [comment]
Any solution?
