### ISSUE TITLE
Bug when I used show case

### ISSUE THREAD

**Issue by neonlee** [SimformSolutionsPvtLtd/flutter_showcaseview#372]
I'm using gorouter as navigation and I've implemented the showcase to do a tutorial on the app's usability, but it doesn't work.

I'm using the latest version of flutter and the latest version of showcase;

I did a decoupling of the showcase;

any tips on how to proceed?

**Comment by ujas-m-simformsolutions** [comment]
can you please share your implementation and also error you are getting

**Comment by neonlee** [comment]
import 'package:app/core/drivers/localstorage/local_storage.dart';
import 'package:app/core/ui/components/cards/widget_description.dart';
import 'package:flutter/material.dart';
import 'package:showcaseview/showcaseview.dart';
import 'package:get_it/get_it.dart';

class CustomShowCase {
  static bool _firstAccess = false;
  CustomShowCase._();

  static void setFistAccess(bool value) {
    _firstAccess = value;
  }

  static Widget showCaseWidget({
    required Widget widget,
  }) {
    return ShowCaseWidget(
      enableShowcase: _firstAccess,
      onFinish: () {
        LocalStorage localStorage = GetIt.I.get();
        localStorage.save(completeFirstAccess, 'true');
        _firstAccess = false;
      },
      onComplete: (index, key) {},
      builder: Builder(
        builder: (context) {
          return widget;
        },
      ),
    );
  }

  static const _height = 100.0;
  static const _width = 150.0;

  static Widget showCaseWithWidget({
    required GlobalKey key,
    required Widget widget,
    void Function()? onTargetClick,
    String? textBody,
    String? textTitle,
    double height = _height,
    double width = _width,
  }) {
    return Showcase.withWidget(
      key: key,
      container: WidgetDescription(
        textBody: textBody,
        textTitle: textTitle,
        height: height,
        width: width,
      ),
      height: height,
      width: width,
      onTargetClick: onTargetClick,
      child: widget,
    );
  }

  static Widget showCase({
    required GlobalKey key,
    required Widget widget,
    required String textBody,
    void Function()? onToolTipClick,
  }) {
    return Showcase(
      key: key,
      description: textBody,
      onToolTipClick: onToolTipClick,
      child: widget,
    );
  }

  static void startShowCase(
    BuildContext context,
    List<GlobalKey<State<StatefulWidget>>> widgetIds,
  ) {
    if (_firstAccess) {
      ShowCaseWidget.of(context).startShowCase(widgetIds);
    }
  }

  static void next(BuildContext context) {
    ShowCaseWidget.of(context).next();
  }

  static void previous(BuildContext context) {
    ShowCaseWidget.of(context).previous();
  }
}

I did a decoupling of the showcase; in this file, after I try to call this in my routes 


 GoRoute(
        path: NamedRoutes.capturedRoute,
        builder: (BuildContext context, GoRouterState state) =>
            CustomShowCase.showCaseWidget(
          widget: const ScreenCaptured(),
        ),
      ),



but not working. nothing appears on the screen.


I try to call this CustomShowCase.showCaseWidget in my screen to, but no appears to.

**Comment by ujas-m-simformsolutions** [comment]
This issue looks like can be resolved resolved with suggestion from this #378. I'm going to close this issue but feel free to open a new one.
