### ISSUE TITLE
Please Provide Showcaseview context

### ISSUE THREAD

**Issue by Eashubh128** [SimformSolutionsPvtLtd/flutter_showcaseview#379]

**Comment by osama450** [comment]
but this in your MaterialApp
_builder: (BuildContext context, Widget? child) {
                  return Overlay(
                    initialEntries: [
                      OverlayEntry(
                        builder: (context) => ShowCaseWidget(
                          builder: Builder(
                            builder: (context) => child!,
                          ),
                        ),
                      ),
                    ],
                  );
                },_

**Comment by vatsaltanna** [comment]
@Eashubh128 Please apply the answer from this problem. #324 


Closing this issue for now, feel free to reopen it if the issue still persists.
