### ISSUE TITLE
Failed assertion: line 5540 pos 12: '_children.contains(child)': is not true.

### ISSUE THREAD

**Issue by vyapariapp** [SimformSolutionsPvtLtd/flutter_showcaseview#38]
> ════════ (3) Exception caught by widgets library ═══════════════════════════════════════════════════
> 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5540 pos 12: '_children.contains(child)': is not true.
> The relevant error-causing widget was: 
>   Container file:///home/midhilajm/Downloads/flutte /lib/vendor/order_listing.dart:149:9
> ════════════════════════════════════════════════════════════════════════════════════════════════════
> 
> ════════ (4) Exception caught by widgets library ═══════════════════════════════════════════════════
> Duplicate GlobalKey detected in widget tree.

```
 @override
  void initState() {
    super.initState();
    //Start showcase view after current widget frames are drawn.
    WidgetsBinding.instance.addPostFrameCallback((_) =>
        ShowCaseWidget.of(context).startShowCase([_one, ]));
  }
```

```
Container(
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Showcase(
              key: _one,
                title: 'Menu',
                description: 'Click here to see menu options',
                child: Icon(
                  Icons.menu,
                  color: Colors.black45,
                ),
              ),
              Icon(Icons.mood_bad,size: 80,),
              Text("No order found",style: TextStyle(fontSize: 22),),

              FlatButton(child: Text("Retry"),onPressed: (){
                print("code for check for any new order");
              },)
            ],
          ),

        ),
      )
```

**Comment by 4RSIM3R** [comment]
Same Problem Here, In My Case I Just Trying To Close All Stream When Back Button Pressed
