### ISSUE TITLE
RenderCustomMultiChildLayoutBox object was given an infinite size during layout

### ISSUE THREAD

**Issue by kaseyrossanderson** [SimformSolutionsPvtLtd/flutter_showcaseview#381]
I am getting the following error:

```RenderCustomMultiChildLayoutBox object was given an infinite size during layout.```

Everything was working fine before I upgraded the plugin, but now I get the above error no matter what I put a showcase widget around (text button, text, navigation, etc.).

The version that is working for me (which I've reverted to for now: 

```showcaseview: ^2.0.3```

The version that is not working that I've tested upgrading to:

```flutter_showcaseview: ^2.1.3```

In my main.dart I wrap my GetMaterialApp() with the ShowCaseWidget so that I don't have to call it everywhere else on the app. I've tried adding it to the individual page instead but that didn't help any. I'm not getting the no context error.. so I think the ShowCaseWidget is initializing.. it's just having issues with the overlay for some reason.

One more important note: This is for web.

**Comment by ujas-m-simformsolutions** [comment]
flutter_showcaseview & showcaseview aren't the same package. `showcaseview` is the correct one so use only this one.
