### ISSUE TITLE
The target element is not focused properly on flutter web which has side space

### ISSUE THREAD

**Issue by Tamrizki** [SimformSolutionsPvtLtd/flutter_showcaseview#383]
**Describe the bug**

The target element is not focused properly for Flutter web which has side space like below. 

**Screenshots**

![post](https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/assets/37837944/8e7c74e7-535d-4a1e-8e79-43139926112f)

**Desktop (please complete the following information):**

**Comment by ujas-m-simformsolutions** [comment]
Please review this #378 pinned issue and see if it helps.
