### ISSUE TITLE
crash on firebase Crashlytics

### ISSUE THREAD

**Issue by thailocnexle** [SimformSolutionsPvtLtd/flutter_showcaseview#385]
<img width="895" alt="Screenshot 2023-08-03 at 2 37 47 PM" src="https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/assets/102008319/ea06d4ad-190c-49ec-a8cb-da70900f83a0">
<img width="1265" alt="Screenshot 2023-08-03 at 2 48 05 PM" src="https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/assets/102008319/4ffce296-eeed-4b07-aaeb-625dea7d0dbf">

**Comment by aditya-chavda** [comment]
Thank you, @thailocnexle, for bringing up this issue.

I truly appreciate the effort you've put into providing screenshots that helped me identify the source of this error. To further assist in investigating this matter thoroughly, I kindly request you to share the complete stacktrace with me.

Given that I'm currently unable to replicate the issue on my end, I would be extremely grateful if you could provide me with a high-level overview of how you're utilizing the showcaseview package within your code. This additional context will greatly aid in my understanding of the problem and in offering an effective solution.

**Comment by aditya-css** [comment]
@thailocnexle Closing this issue as a similar issue (#366 ) with more information is already open.
