### ISSUE TITLE
Hi.thnaks for your perfect package.is it possible to disable barrier click?

### ISSUE THREAD

**Issue by mahdiqdi** [SimformSolutionsPvtLtd/flutter_showcaseview#387]
i want to only target position should be clickable not barrier part
is it possible?
for example user should click a level to go to next page and then come back but user click on barrier part and skip this level
there is property in ShowCaseWidget but i want this feature in showCase cause i want only a level should not be clickable

**Comment by ujas-m-simformsolutions** [comment]
Hey @mahdiqdi, ShowCaseWidget has parameter called `disableBarrierInteraction` which you can set to **true** to disable barrier clicks and for getting more info on other parameters please check [Documentation](https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/blob/master/README.md).

**Comment by mahdiqdi** [comment]
no you did not figure out what is my problem
i know there is disableBarrierInteraction property
but when i disable it all levels ignore click
for example i want level one be clickable but level two not be clickable

**Comment by ujas-m-simformsolutions** [comment]
reopening for further investigation.

**Comment by vatsaltanna** [comment]
Hello, @mahdiqdi If I understand you accurately, you are proposing that each showcase should have the option to enable or disable barrier control. Is it correct?

**Comment by mahdiqdi** [comment]
@vatsaltanna yes exactly

**Comment by vatsaltanna** [comment]
All right. We will investigate the feasibility of this and keep you updated. Also, this package is open for external contributions, so if you want to try to implement the functionality, that would be great.

**Comment by mahdiqdi** [comment]
thanks man
i will try my best to help you accomplish this feature
