### ISSUE TITLE
can't scroll horizontal list with showcase

### ISSUE THREAD

**Issue by baris-semerci** [SimformSolutionsPvtLtd/flutter_showcaseview#388]
**Describe the solution you'd like**
I want to scroll one horizontal list inside showcase widget.

**Comment by jaiminrana05** [comment]
Hello @baris-semerci, Could you please provide more information on the issue you are experiencing?

**Comment by Sahil-Simform** [comment]
Hi @baris-semerci, if you add `disableDefaultChildGestures = true` in the showcase widget you can scroll the horizontal list. and if you want to add a horizontal scroll list in showCase toolTip you can use`Showcase.withWidget` to provide your custom widget.
