### ISSUE TITLE
Scaffold.geometryOf() must only be accessed during the paint phase. V^2.0.2

### ISSUE THREAD

**Issue by dootix-gael** [SimformSolutionsPvtLtd/flutter_showcaseview#389]
**Describe the bug**
The following Flutter error occurred when we passed the following showCase steps very quickly.
FlutterError: Scaffold.geometryOf() must only be accessed during the paint phase.
The ScaffoldGeometry is only available during the paint phase, because its value is computed during the animation and layout phases prior to painting.

**To Reproduce**
1. Have multiple (+4 steps) stages for the showCase
2. Click on the screen quickly (-1sec interval) to move on to the next showCase
3. See the error : FlutterError: Scaffold.geometryOf() must only be accessed during the paint phase.
The ScaffoldGeometry is only available during the paint phase, because its value is computed during the animation and layout phases prior to painting.

![2023-08-23-152330](https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/assets/88476251/277de6b0-0b6c-46f8-8f04-7968f2f604e6)

**Expected behavior**
The behavior is completely correct, it only raises the error cited above which should not occur

**Smartphone (please complete the following information):**
 - Device: [Xiaomi 11T]
 - OS: [Android 13 TP1A.220624.014]
 - Version MIUI [14.0.5.0 (TKWEUXM)]

**Additional context**
The error was detected thanks to Sentry's service. No visual error is perceived during the application run.

**Comment by vatsaltanna** [comment]
Hi @dootix-gael, I belive showcaseview package does not use scaffold internally. So I cause of this issue might be something else.

**Comment by dootix-gael** [comment]
After a few tests, the problem arises when `onFinish()` calls `Navigator.maybePop(context)`.

Clicking too quickly. During the `oneFinish()`, I get the impression that maybePop is executed at the same time as the last next or the function that checks if it's the end of my showCase. Hence, the error message *"The ScaffoldGeometry is only available during the paint phase, because its value is computed during the animation and layout phases prior to painting."*

Is there another way to perform a Navigator.maybePop() in the `onFinish()` function? Does the package correctly handle performing this action in the `onFinish()` function?

I've also noticed that this minor bug is only present when the application is in debug mode. If I build the app, this doesn't happen. I think it's just a question of timing, which is very minor...

![2023-08-25-111725](https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/assets/88476251/07305ce0-4963-4df0-9af6-212706bcb1cf)
