### ISSUE TITLE
Showcase view for next widget not visible if index for previous widget not found

### ISSUE THREAD

**Issue by umar-stride-studio** [SimformSolutionsPvtLtd/flutter_showcaseview#393]
Let's have an example, I have 5 keys for 5 different widgets in Stateful Widget.

```
List<GlobalKey<State<StatefulWidget>>> introKeys = [];    
introKeys = [detailKey,mapKey,shareKey,attendeesKey,joinKey];

```
Let's say if 3rd widget depend upon a specific condition. For example:

```
 isUserAdmin?ShowCaseView(
      globalKey: shareKey,
      padding: const EdgeInsets.all(0),
      onSkipClick: (){
        ShowCaseWidget.of(context).dismiss();
      },
      onNextClick: (){
        ShowCaseWidget.of(context).next();
      },
      ......
    ):Container(
        child:....
     )

```
If this condition doesn't satisfy then 3rd show case view doesn't show which is expected but after then showcase view is dismissed, if 3rd widget condition not found then 4th widget showcase doesn't show up.

https://youtube.com/shorts/OlDxsReQKgE?feature=share

https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/assets/116542608/05ac0362-ec58-4db0-b459-48ea0e87c308

I have attached the video in which you can see behavior of showcaseview for both case if widget found and widget not found

**Comment by umar-stride-studio** [comment]
waiting for your response

**Comment by jaiminrana05** [comment]
Hello @umar-stride-studio, I understand you are attempting to skip the showcase based on a condition. You may apply the same condition to the `introKeys ` List instead of placing it on the widget. 

```
List<GlobalKey<State<StatefulWidget>>> introKeys = [];    
introKeys = [
    detailKey,
    mapKey,
    if(isUserAdmin)shareKey,
    attendeesKey,
    joinKey,
];

```

**Comment by aditya-css** [comment]
Hey @umar-stride-studio, Instead of conditionally passing and removing `GlobalKey` to and from a widget, please try to update the `introKeys` list and removing the `GlobalKey` from it based on the condition.

You're currently seeing this behaviour as you are removing a `GlobalKey` from the widget but the list passed to `ShowCaseWidget.of(context).startShowCase` still has that `GlobalKey` which is not attached to any widget.
