### ISSUE TITLE
add left & right to TooltipPosition

### ISSUE THREAD

**Issue by SPSpisoft** [SimformSolutionsPvtLtd/flutter_showcaseview#399]
Please add the option to specify left and right to TooltipPosition.
We have a widget that covers the entire height, and cannot use the top or bottom option to display the Tooltip.

**Comment by SaiZayarHtet7** [comment]
Yes We need it for the widget with the height of device, because the  tooltips disappear outside

**Comment by aditya-css** [comment]
Closing this issue as it is duplicate of #54.
