### ISSUE TITLE
Unable to find an alternate option for this code "ShowCaseWidget.of(context).disableBarrierInteraction = true"

### ISSUE THREAD

**Issue by akshaym-weave** [SimformSolutionsPvtLtd/flutter_showcaseview#402]
**Describe the bug**
Unable to find an alternate option for this code "ShowCaseWidget.of(context).disableBarrierInteraction = true"
in the latest plugin version.

**Comment by StevePhuc** [comment]
ShowCaseWidget has parameter called disableBarrierInteraction which you can set to true to disable barrier clicks and for getting more info on other parameters please check [Documentation](https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/blob/master/README.md).

**Comment by aditya-css** [comment]
@akshaym-weave Please let us know if you are still facing any difficulties after seeing @StevePhuc comment.
