### ISSUE TITLE
Click on Barrier close the Showcase with Showcase widget.

### ISSUE THREAD

**Issue by FabriceACohen** [SimformSolutionsPvtLtd/flutter_showcaseview#407]
Showcase widget should have a disableBarrierInteraction property as for ShowCaseWidget.

The onTap of the barrier get a the default ShowCaseWidget parameter (false) so if the user click on the barrier the showcase closes since the onTap launch _nextIfAny() that closes the widget.

MoreOther since all this is in the State class that is private no way to overwrite the class...

Would it be possible to add this proposerty and juste change one line of code : 
   if (!showCaseWidgetState.disableBarrierInteraction) {.   WOULD BECOME :    if (!widget.disableBarrierInteraction) {

**Comment by aditya-css** [comment]
Hi @FabriceACohen, please have a look at an already open PR #392  that I believe addresses the same issue that you have mentioned here. Feel free to let me know if that's not the case.
