### ISSUE TITLE
Misalignment Problem Following OS Keyboard Display and Dismissal

### ISSUE THREAD

**Issue by realDiegoR** [SimformSolutionsPvtLtd/flutter_showcaseview#408]
**Describe the bug**
While attempting to showcase a TextField widget situated within a SingleChildScrollView & Column setup, I encounter an issue. The said widget is positioned near the bottom of the Column, and consequently, the screen. Upon filling the TextField and the OS keyboard appearing, the widget (along with the showcase target) naturally rises. However, upon dismissing the keyboard, the showcase target becomes misaligned (appearing above the intended widget). This occasionally leads to a dysfunctional UI. Interestingly, performing a Hot Reload resolves the alignment, restoring it to the correct position.

**To Reproduce**
1. Create a Scaffold -> SingleChildScrollView -> Column
2. Showcase a TextField widget that is at the bottom of the device screen, and set `disableDefaultTargetGestures`  to `true`
3. Tap the TextField, so the OS keyboard is displayed and then close it.

**Expected behavior**
The showcase target maintains its vertical alignment after displaying and closing the OS keyboard

**Screenshots**

Before displaying and closing the OS keyboard
<img width=220 src='https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/assets/87043777/c3d29db1-113a-417d-a15c-91da5166feec' />

After displaying and closing the OS keyboard
<img width=220 src='https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/assets/87043777/9ddb8897-70de-4a03-9039-153b4ebaf1df' />

**Smartphone (please complete the following information):**
 - Device: Samsung S21 FE
 - OS: Android 14

**Comment by realDiegoR** [comment]
Oh, also I just discovered that when the keyboard is displayed on screen, it lets me scroll vertically all over the screen without restrictions

**Comment by aditya-css** [comment]
Thank you for raising this issue @realDiegoR. For general use case of showcasing application features, such keyboard interaction won't be needed. If you keep `disableDefaultTargetGestures` as `false` then you would not run into any issues in the latest code of this package. I am closing this as of now with the aforementioned reason.
