### ISSUE TITLE
Showcase overlays on next page even after completion

### ISSUE THREAD

**Issue by Wolfof420Street** [SimformSolutionsPvtLtd/flutter_showcaseview#421]
**Describe the bug**
After viewing the showcase one page, when I navigate to another page, the Showcaase still overlays on the next page on widgets that are not in the current context. 

**To Reproduce**
1.Start ShowCase
2. Complete Showcase
3. Navigate to next page

**Expected behavior**
Showcase is dismissed once I navigate to a new page.

**Comment by aditya-css** [comment]
Hello @Wolfof420Street,
Please make sure to call `ShowCaseWidget.of(context).dismiss()` before you navigate to the next page, or if you are using `onTargetClick` then make sure to pass `disposeOnTap` as `true`. Closing this issue with this comment, feel free to reopen if the provided solution doesn't work for you.
