### ISSUE TITLE
Unhandled breaking change in v2.1.0

### ISSUE THREAD

**Issue by fstof** [SimformSolutionsPvtLtd/flutter_showcaseview#425]
**Describe the bug**
Updating to the latest version (2.1.0) is breaking stuff on our side as the use of `ViewPadding` is not available on previous versions of Dart SDK

**To Reproduce**
1. Create flutter project with dart "sdk < 3"
2. include `showcaseview: 2.1.0`
3. running app should fail as reference to `ViewPadding.zero` does not exist

**Expected behavior**
Should work

**Additional context**
The latest version of this sdk should version the latest release as a "breaking change" version update (3.0.0) as well as updating the minimum sdk version to > 3.0.0 so dependants don't fail if pubspecs reference `^2.0.0`

Ideally a working (fixed)version should be published under the 2.x.x version in order to fix breaking dependencies then a new major version can be published with new changes

**Comment by aditya-css** [comment]
Thank you @fstof for bringing this into our notice. It was a slip from our end, have created PR #427 with the fix. You can use that PR till we release a new version with that commit.

**Comment by fstof** [comment]
Thanks for this @aditya-css 
Do we have an ETA for the release of this?
