### ISSUE TITLE
The target element is not focused properly with responsive_framework: ^0.2.0 

### ISSUE THREAD

**Issue by BrainDjuice** [SimformSolutionsPvtLtd/flutter_showcaseview#426]
**Description:**

I'm experiencing an issue where the target element is not focused properly when using the `responsive_framework` package (version ^0.2.0) in my Flutter app.

<img width="434" alt="Screenshot 2024-04-22 at 11 05 16" src="https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/assets/45123241/9e8e7504-a2d5-4ecf-875b-704abf8ca5ed">

**Steps to reproduce:**

`MaterialApp(
      builder: (context, child) => ResponsiveWrapper.builder(
        BouncingScrollWrapper.builder(context, child!),
        maxWidth: 1200,
        minWidth: 450,
        defaultScale: true,
        breakpoints: [
          const ResponsiveBreakpoint.resize(450, name: MOBILE),
          const ResponsiveBreakpoint.autoScale(800, name: TABLET),
          const ResponsiveBreakpoint.resize(1920, name: DESKTOP),
          const ResponsiveBreakpoint.autoScale(2460, name: "4K"),
        ],
        background: Container(
          color: const Color(0xFFF5F5F5),
        ),
      ),
      debugShowCheckedModeBanner: false,
      title: 'Water Tracker',
      home: ShowCaseWidget(
        builder: Builder(
          builder: (context) => HomePage(),
        ),
      ),
    );`

**Expected behavior:**

The target element should be focused properly.

**Actual behavior:**

The target element is not focused properly.

**Comment by aditya-css** [comment]
Hello @BrainDjuice, On initial inspection, I have found that setting the `defaultScale` parameter to `false` in your provide code seems to resolve the issue. Please see if that would work for you. I'll take a deeper look later. Thanks.

**Comment by BrainDjuice** [comment]
Thank you, setting `defaultScale` to `false` does indeed resolve the issue for me.

**Comment by YonatanSegura97** [comment]
Any solution for the newest version of responsive framework? I have the same issue. But my Responsive Framework version does not have `defaultScale` field.
https://github.com/Codelessly/ResponsiveFramework/blob/master/migration_0.2.0_to_1.0.0.md
