### ISSUE TITLE
any one can help ?

### ISSUE THREAD

**Issue by Basemshawwa** [SimformSolutionsPvtLtd/flutter_showcaseview#430]
when run app this error was showen

<img width="1399" alt="Screenshot 2024-04-28 at 7 12 10 PM" src="https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/assets/45998555/94a3c1a9-2949-4bb9-9ecc-40b29845f5d3">

**Comment by aditya-css** [comment]
It seems like you are using Dart version lesser than 3.0.0. This has already brought to notice by issue #425 and has been fixed in PR #427. Can you please use that branch until we merge it and release a new version with that fix? Closing this issue with that being requested.

**Comment by Basemshawwa** [comment]
thank you
