### ISSUE TITLE
Missing Text Style headline6 and subtitle2 after Flutter 3.22

### ISSUE THREAD

**Issue by chandrabezzo** [SimformSolutionsPvtLtd/flutter_showcaseview#434]
**Describe the bug**
Upgrade your Flutter SDK to the latest, then you will found an issue missing deprecated text stlyle for headline6 and subtitle2

**To Reproduce**
1. Upgrade your Flutter SDK to 3.22
2. Run example

**Expected behavior**
Application runnable when use flutter_showcaseview as dependency

**Screenshots**
![Screenshot 2024-05-14 at 09 03 06](https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/assets/16184998/cad9e6e3-75e7-4138-9d42-75897d064dce)

**Additional context**
If users not updated to the latest Flutter SDK 3.22 this issue not happens

**Comment by JgomesAT** [comment]
Same problem, this attributes ara not valid for flutter 3.22

**Comment by Yegorisa** [comment]
Yep, same problem here

**Comment by chandrabezzo** [comment]
This issue will solved in PR #433

**Comment by JgomesAT** [comment]
Is there a scheduler available to publish this PR to pub.dev?

**Comment by eduardofcr** [comment]
same problem after upgraded flutter

**Comment by ahmed-3li** [comment]
Same issue here when upgrading to Flutter 3.22.0 • channel stable

**Comment by Lerobindesbois** [comment]
Same here 

Error (Xcode): ../../.pub-cache/hosted/pub.dev/showcaseview-2.1.1/lib/src/tooltip_widget.dart:156:14: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.

**Comment by aditya-css** [comment]
Fixed by PR #433
