### ISSUE TITLE
Hi there is I have bug on my code about showCase

### ISSUE THREAD

**Issue by cengizxturkes** [SimformSolutionsPvtLtd/flutter_showcaseview#436]
Plugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
../../../.pub-cache/hosted/pub.dev/showcaseview-2.1.1/lib/src/tooltip_widget.dart:156:14: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
            .headline6!
             ^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/showcaseview-2.1.1/lib/src/tooltip_widget.dart:163:14: Error: The getter 'subtitle2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle2'.
            .subtitle2!
             ^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/showcaseview-2.1.1/lib/src/tooltip_widget.dart:463:50: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
                                                .headline6!
                                                 ^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/showcaseview-2.1.1/lib/src/tooltip_widget.dart:484:48: Error: The getter 'subtitle2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle2'.
                                              .subtitle2!
                                               ^^^^^^^^^

**Comment by Agndv** [comment]
i'm also facing this same issue, please resolve this ASAP
