### ISSUE TITLE
Not Support Flutter 3.22

### ISSUE THREAD

**Issue by Obada2020** [SimformSolutionsPvtLtd/flutter_showcaseview#451]
../../.pub-cache/hosted/pub.dev/showcaseview-2.1.1/lib/src/tooltip_widget.dart:156:14: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
            .headline6!

**Comment by aditya-css** [comment]
This is been resolved by PR #433. We will release with that fix soon, until then you can use master branch's checkout.
