### ISSUE TITLE
titleAlignment property does not work

### ISSUE THREAD

**Issue by junior-ramayo** [SimformSolutionsPvtLtd/flutter_showcaseview#457]
**Describe the bug**
I am applying a TextAlign.center to the titleAlignment property and the Title is not centered.

**Expected behavior**
I would expect the title to appear centered.

<img width="236" alt="Captura de pantalla 2024-06-27 a la(s) 11 06 08 p m" src="https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/assets/84688875/08baf49f-c654-418a-804c-0063d5e287b3">

**Comment by rashi-simform** [comment]
Hello @junior-ramayo, I have updated the name of `titleAlignment` that you have used to `titleTextAlign` and added two new parameters, `titleAlignment` and `descriptionAlignment` that would achieve what you desire.
You can look into this PR and use it until it is released on pub.dev: https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/pull/459

**Comment by Jinsung-viim** [comment]
any update?

**Comment by ankeet7x** [comment]
When is it going to be released? It's already been 4 months since this PR.
