### ISSUE TITLE
Click on the text

### ISSUE THREAD

**Issue by mbfakourii** [SimformSolutionsPvtLtd/flutter_showcaseview#460]
**Is your feature request related to a problem? Please describe.**
Nothing happens when the text is clicked

**Describe the solution you'd like**
I want to go to the next when the text is clicked

**Describe alternatives you've considered**
n/a

**Additional context**
![image](https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/assets/20955005/49e2bcb8-4a1e-4b97-94ee-aa430c078eb3)

**Comment by pawanbangar** [comment]
@mbfakourii you need to use onToolTipClick method to customize behaviour of tooltipClicked
you can do
`ShowCaseWidget.of(context).next() ` in callback to achive your functionality.

**Comment by aditya-chavda** [comment]
Hello @mbfakourii,
Please refer to solution provided by @pawanbangar above. Feel free to let us know if you run into any issues or need more explanation.

Thanks @pawanbangar for providing correct information!

**Comment by mbfakourii** [comment]
> Hello @mbfakourii, Please refer to solution provided by @pawanbangar above. Feel free to let us know if you run into any issues or need more explanation.
> 
> Thanks @pawanbangar for providing correct information!

Yes, the problem is solved, Thanks
