### ISSUE TITLE
How to trigger the target's default click behavior.

### ISSUE THREAD

**Issue by RaymondGsc** [SimformSolutionsPvtLtd/flutter_showcaseview#465]
**Describe the bug**
Here is my code, I set disableDefaultTargetGestures to false but I found I still cannot trigger the target's default click event. I have to click the target only to dismiss the showcase first , then the target can be clickable.

BTW, the I pass a clickable list to the "child" attribute.

![image](https://github.com/user-attachments/assets/b61f0d87-c1de-4f89-b78b-fd6473dbf50e)

**Comment by pawanbangar** [comment]
@RaymondGsc it might have caused by https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/pull/412
fix PR @aditya-css if i raise PR with fix, will you merge?

**Comment by aditya-chavda** [comment]
Hi @RaymondGsc,
When you set `disposeOnTap` as `true` then you have provide `onTargetClick` and manually handle all the actions (next, dispose, etc). Referring document comment for those properties would help understanding those, please see image attached. 

As for your problem's solution, please set `disposeOnTap` as `false` and not pass anything for `onTargetClick` when you desire the default click events.

<img width="555" alt="image" src="https://github.com/user-attachments/assets/b69a4e77-1a28-4ec7-b0d7-37a845dcc4d3">
