### ISSUE TITLE
OverlayColor and OverlayOpacity don't work if widget is partially off-screen

### ISSUE THREAD

**Issue by lunaticcoding** [SimformSolutionsPvtLtd/flutter_showcaseview#47]
# Behaviour
If the widget I encapsulate in the Showcase widget, the description and title all display correctly but the OverlayColor and OverlayOpacity don't show up at all. If I add a delay and scroll the widget into full view, then the overlay works again.

**Comment by JigneshPatel23** [comment]
Yes, facing the same issue.

**Comment by GrahamDi** [comment]
Ideally if the widget being showcased eg. a side drawer item, is off the screen due to small screen size or landscape orientation then the screen should be scrolled (assuming it is scrollable) to show the 'hidden' widget.
