### ISSUE TITLE
Running issue

### ISSUE THREAD

**Issue by alig87** [SimformSolutionsPvtLtd/flutter_showcaseview#471]
s] ../../../AppData/Local/Pub/Cache/hosted/pub.dev/showcaseview-2.1.1/lib/src/tooltip_widget.dart:463:50: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
[        ]  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/D:/Flutter/flutter/packages/flutter/lib/src/material/text_theme.dart').
[        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
[        ]                                                 .headline6!
[        ]                                                  ^^^^^^^^^
[        ] ../../../AppData/Local/Pub/Cache/hosted/pub.dev/showcaseview-2.1.1/lib/src/tooltip_widget.dart:484:48: Error: The getter 'subtitle2' isn't defined for the class 'TextTheme'.
[        ]  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/D:/Flutter/flutter/packages/flutter/lib/src/material/text_theme.dart').
[        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle2'.

**Comment by aditya-chavda** [comment]
Hello @alig87,
Please use the latest version of showcase view (v3.0.0) as to avoid running into this issue. Thanks!
