### ISSUE TITLE
 Error: headline6 getter is undefined in TextTheme class in showcaseview package version 2.1.1

### ISSUE THREAD

**Issue by nahitmamati** [SimformSolutionsPvtLtd/flutter_showcaseview#474]
../../../.pub-cache/hosted/pub.dev/showcaseview-2.1.1/lib/src/tooltip_widget.dart:156:14: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.

**Comment by aditya-css** [comment]
@nahitmamati  Please use the latest version (3.0.0) of this package for resolution of this issue.
