### ISSUE TITLE
When arrow on the top right of bubble it should not show a rounded corner

### ISSUE THREAD

**Issue by basvdijk** [SimformSolutionsPvtLtd/flutter_showcaseview#475]
**Describe the bug**

When there is an item on the far right of the screen. The bubble should not have a rounded corner on the top right.

**To Reproduce**
Add an action button to the far right of the toolbar

**Expected behavior**
No rounded corner on the top right when the arrow is shown on the right. Guess this could be the same with the left side.

**Screenshots**
![image](https://github.com/user-attachments/assets/24639138-fb6b-4e25-ad39-d512cc00033d)

**Desktop (please complete the following information):**
 - OS: iOS
 -
**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: 17

**Comment by aditya-css** [comment]
Hi @basvdijk,

Can you please let me know which version of this package are you using? 

Also, please share with me a minimal reproducible code so that I can look more into this since the issue is not seen in the example code. Thanks.

**Comment by basvdijk** [comment]
@aditya-css using package version 3.3.0

This is example code for an action button in the appBar aligned on the right side:

```dart
return Scaffold(
  drawer: const DrawerMenu(),
  appBar: AppBar(
    iconTheme: const IconThemeData(color: Colors.white),
    backgroundColor: Colors.brown,
    actions: [
      Showcase(
        key: _tourRestart,
        description: 'restart',
        child: IconButton(
          icon: const Icon(Icons.refresh),
          onPressed: () {}
        ),
      ),
    ],
  ),
```

**Comment by Sahil-Simform** [comment]
Hi @basvdijk, This PR will provide a way to fix this issue by adjusting the margin around the tooltip. For now, there are a couple of ways you can fix this issue using the released version.
1. You can adjust the border radius of the tooltip. I believe a radius of '4' will work fine on the corner where the arrow is positioned.
2. You can provide padding to your action widget and the arrow will adjust automatically.
