### ISSUE TITLE
Showcase not working on drawer hamburger menu icon

### ISSUE THREAD

**Issue by basvdijk** [SimformSolutionsPvtLtd/flutter_showcaseview#476]
**Describe the bug**

It looks like the widget is not working when applied to the drawer widget of material.

```dart
return Scaffold(
  drawer: Showcase(
    key: _navMenu,
    description: 'help and contact,
    child: const DrawerMenu(),
  ),
```

**To Reproduce**
- Create default Flutter material app.
- Add Showcase to the menu drawer.

**Expected behavior**
The showcase bubble to show on the "hamburger menu"

**Screenshots**
n/a

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: 17.5

**Comment by aditya-css** [comment]
Hello @basvdijk,

Can you please clarify if you desire showcase on the hamburger menu icon or the drawer itself, as the title mentions icon but the code you have shared has added showcase on top of the drawer?

If you want the showcase on just the icon then please wrap the hamburger menu icon widget with showcase widget. Thanks.

**Comment by basvdijk** [comment]
@aditya-css 

> Can you please clarify if you desire showcase on the hamburger menu icon or the drawer itself, as the title mentions icon but the code you have shared has added showcase on top of the drawer?

I would like to add a showcase on the hamburger menu icon itself. 

> If you want the showcase on just the icon then please wrap the hamburger menu icon widget with showcase widge

In my code the showcase is added to the drawer, since there is no hamburger menu icon to add it to. I guess when adding a drawer the icon is handled by Flutter Material?

**Comment by Sahil-Simform** [comment]
Yes if you have not provided any ```leading``` widget in ```AppBar``` and provided a ```drawer``` in scaffold it will automatically add a Icon to open a Drawer so if you need showcase that drawer icon you need to provide a your own widget and wrap that in the showcase.
Here is a Basic AppBar Widget to show Drawer Icon with ShowCase:

```dart
AppBar(
   title: const Text('hello'),
   leading: Showcase(
          key: GlobalKey(), //<--- Your showcase key goes here,
          title: 'Drawer',
          description: 'Click here to open drawer',
          targetShapeBorder: const CircleBorder(),
          child: Builder(builder: (context) {
            return IconButton(
              icon: const Icon(Icons.menu),
              onPressed: () => Scaffold.of(context).openDrawer(),
            );
          }),
        ),
      ),
```

**Comment by basvdijk** [comment]
@Sahil-Simform thanks!
