### ISSUE TITLE
AnimatedSwitcher using problem

### ISSUE THREAD

**Issue by alikperislam** [SimformSolutionsPvtLtd/flutter_showcaseview#479]
If I wrap with ShowCase when using AnimatedSwitcher, the animation does not work.

**Comment by Sahil-Simform** [comment]
Wrap AnimatedSwitcher with Showcase Widget then it will work.
Reason: We provide the key to Showcase widget so that widget will be the same for all the time and animation won't happen

**Comment by aditya-css** [comment]
@alikperislam Closing this issue provided that @Sahil-Simform's comment would solve your issue. Please feel free to reopen if you still need any assistance.
