### ISSUE TITLE
Show a custom widget inside showcaseWidget instead of title/description

### ISSUE THREAD

**Issue by basvdijk** [SimformSolutionsPvtLtd/flutter_showcaseview#485]
**Is your feature request related to a problem? Please describe.**
I have an indicator widget which can have several colors. Now I need to write it as text in the description field e.g. white = clean, blue = dirty, red = needs replacement.

I more visual way would make it clearer. For example 3 rows where each row consists of a colored dot followed by some text.

**Describe the solution you'd like**
Something like:

```dart
Showcase(
  key: _tourFirstListItem,
  contentChild: 
  
  Column(children: [
    Row(children: [
        Dot('red')
        Text('Clean'),
    ]),
    Row(children: [
        Dot('blue')
        Text('dirty'),
    ]),
  ]),
  child: ...
  ),
)
```

**Describe alternatives you've considered**
Writing it as text in the description property

**Comment by vatsaltanna** [comment]
Hi @basvdijk, try `Showcase.withWidget` as mentioned in the readme.

**Comment by basvdijk** [comment]
@vatsaltanna When using `Showcase.withWidget` I have to build the complete bubble with pointing arrows myself. I just want to replace the content with another widget.

**Comment by vatsaltanna** [comment]
Thank you for your suggestion! I understand that you’d prefer a different approach, but unfortunately, customizing the tooltip in that way isn’t something we have planned in the near future. At the moment, the alternative I suggested is the best available option. However, I appreciate your feedback, and we'll keep it in mind for potential updates. Thanks again for understanding!

**Comment by vatsaltanna** [comment]
Unfortunately, no. Internally, it calculates based on the text, and it’s not possible to remove that behavior at the moment. That’s why I suggested using a custom implementation instead of modifying the existing one.

I’ll close this issue now, as you’ve already achieved your requirement with a custom showcase. Thanks for understanding, and I appreciate your support. Keep contributing!
