### ISSUE TITLE
web overlayOpacity not working

### ISSUE THREAD

**Issue by zkx2020** [SimformSolutionsPvtLtd/flutter_showcaseview#58]

**Comment by BirjuVachhani** [comment]
@zkx2020 It would be great if you could provide more information about this. Like some code and images to make it clear what you're saying exactly.

**Comment by maurobotta** [comment]
Hi, In Web generation, there is a visual problem, the dark effect ( on all form )  is not visible

Flutter (Channel beta, 1.21.0-9.2.pre, on Microsoft Windows [Versione 10.0.18363.1082], locale it-IT)

**Comment by ekokratos** [comment]
@BirjuVachhani this is what they meant by Overlay Opacity. The helper text is shown but the showcase (dark) background isn't showing up.

![InkedScreenshot (24)_LI](https://user-images.githubusercontent.com/26033335/95291302-dbbd6c00-088c-11eb-946b-48f2465a4de8.jpg)

**Comment by sanket-simform** [comment]
@zkx2020  @ekokratos 
We're using custom paint to build overlay and custom paint not working properly with CanvasKit so it requires SKIA. 
So currently solution is to use below config and it will work as expected. 

`flutter build web --release --dart-define=FLUTTER_WEB_USE_SKIA=true `
