### ISSUE TITLE
How to use showCase for BottomNavigationBarItem when BottomNavigationBar class accepsts only BottomNavigationBarItem?

### ISSUE THREAD

**Issue by msndvlpr** [SimformSolutionsPvtLtd/flutter_showcaseview#61]
How to use showCase for BottomNavigationBarItem when BottomNavigationBar class accepsts only BottomNavigationBarItem?

**Comment by BirjuVachhani** [comment]
@msndvlpr I am not sure, but maybe you can use it in the `title` or `icon` property of the `BottomNavigationBarItem`.

**Comment by BirjuVachhani** [comment]
@msndvlpr Beware that in Upcoming flutter version, the property `title` is deprecated and they have introduced new property named `label` which is of type `String`. So you won't be able to use `showCase` there anymore.

**Comment by BirjuVachhani** [comment]
@msndvlpr Closing this for now. Feel free to reopen in case you need further help.

**Comment by cdmunoz** [comment]
Is there a way in which the lib works properly with the `BottomNavigationBar`? Because it's impossible to set a `Showcase` widget as part of the `icon` it needs to config itself as an `IconTheme`.
According to the documentation in `BottomNavigationBarItem`:

```dart
  ///Typically the icon is an [Icon] or an [ImageIcon] widget. If another type
  /// of widget is provided then it should configure itself to match the current
  /// [IconTheme] size and color.
```

**Comment by lybur** [comment]
I need this feature too, it's impossible to wrap the Showcase widget in my BottomNavigationBarItem.

**Comment by anshul201** [comment]
I was able to solve it like 

```
 BottomNavigationBarItem(
                icon: Showcase(key: _one, description: "description", child: Icon(Icons.home)),
                label: 'home'.tr,
              )
```

**Comment by OsamaDarabeh** [comment]
Any update related to this issue ?
