### ISSUE TITLE
Highlight Not working when widget is not visible on screen

### ISSUE THREAD

**Issue by TheDev563** [SimformSolutionsPvtLtd/flutter_showcaseview#71]
Highlight to the widget is not working when widget is not visible on the screen. How Highlight will work if widget is in bottom widget of the screen size which is not visible.

**Comment by dumilonz** [comment]
You will have to scroll to the widget so that it is visible.

**Comment by ParthBaraiya** [comment]
Solved in this PR [#192](https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/pull/192)
