### ISSUE TITLE
Showcase inside showDialog() method

### ISSUE THREAD

**Issue by Omar-Belghaouti** [SimformSolutionsPvtLtd/flutter_showcaseview#77]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when having a bug that says "it was called on null" when using it inside showDialog()

**Describe the solution you'd like**
I want to have a Showcase displayed on elements inside a Dialog using a showDialog() method

**Describe alternatives you've considered**
Honestly, I tried to use WidgetsBinding,instance,addPostFrameCallback() inside the builder of showDialog but it didn't work as well.

**Additional context**
![image](https://user-images.githubusercontent.com/48713070/96921575-07586d00-14af-11eb-93a4-23802d14cf85.png)

**Comment by vatsaltanna** [comment]
Hi @Omar-Belghaouti, please add "ShowCaseWidget" as a parent of dialog and start showcase in the builder of "ShowCaseWidget".
here is your updated code.
```
showDialog<void>(
      context: context,
      builder: (context) {
        return ShowCaseWidget(
          builder: Builder(
            builder: (context) {
              WidgetsBinding.instance!.addPostFrameCallback(
                  (_) => ShowCaseWidget.of(context)!.startShowCase([scTest]));
              return Dialog(
                elevation: 14.0,
                child: Padding(
                  padding: EdgeInsets.all(14.0),
                  child: SingleChildScrollView(
                    child: Column(
                      children: [
                        Showcase(
                          key: scTest,
                          title: 'Test',
                          description: 'This is test',
                          child: Text('Test'),
                        ),
                      ],
                    ),
                  ),
                ),
              );
            },
          ),
        );
      },
    );
```
