### ISSUE TITLE
Remove requirement for widgets to have activeWidgetIds

### ISSUE THREAD

**Issue by frankyvij** [SimformSolutionsPvtLtd/flutter_showcaseview#82]
Widgets are reusable across the application, and some widgets in specific context may required to be showcased. Additionally, some widgets simply change behavior based on parameters passed.

I am suggesting to change following implementation in showcase_widget to:
` static activeTargetWidget(BuildContext context) {
      return context
          .dependOnInheritedWidgetOfExactType<_InheritedShowCaseView>()
          ?.activeWidgetIds;
  }` 

Doing so does not break the UI in case a user intends to use Showcase(child: widget), but does not want to use ShowCaseView(builder: ...) for a specific scenario.

**Comment by ManojDvs** [comment]
my app is having this error for the first time launch , but from second time the error dissappears.

**Comment by WwwdMR** [comment]
> my app is having this error for the first time launch , but from second time the error dissappears.

I have the same Issue what is the solution for this?

**Comment by aditya-css** [comment]
@ManojDvs @WwwdMR Can you guys please provide more information on the error that you are receiving so that we would be able to help you more?

**Comment by aditya-css** [comment]
@frankyvij Can you please try to give us few of the scenarios for which you are suggesting such a change so that we can evaluate it better?

**Comment by aditya-css** [comment]
Closing this issue cause of inactivity. Feel free to open a new issue if required.
