### ISSUE TITLE
Size and position

### ISSUE THREAD

**Issue by jagritjkh** [SimformSolutionsPvtLtd/flutter_showcaseview#85]
**Describe the bug**
In BottomNavigationBar, 2nd item has large description box size, the third one becomes vertical.

**Expected behaviour**
All showcases should be of the same size.

**Screenshots**
In this, it's perfect!
![Screenshot_20201211-075531](https://user-images.githubusercontent.com/32562337/101853838-5a34d380-3b86-11eb-98fc-b9cf7604a36c.jpg)

In this, the horizontal padding increases.
![Screenshot_20201211-075533](https://user-images.githubusercontent.com/32562337/101853898-7769a200-3b86-11eb-8859-41ea79c21e70.jpg)

In this, idk what happened to it!
![Screenshot_20201211-075536](https://user-images.githubusercontent.com/32562337/101853928-83556400-3b86-11eb-97e3-be7c6c1a599b.jpg)

And in this, it becomes normal again.
![Screenshot_20201211-075542](https://user-images.githubusercontent.com/32562337/101853971-90725300-3b86-11eb-953d-2db37b35026c.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. UBUNTU]

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 7T]
 - OS: [e.g. Android 10]

**Comment by Armoured-Door-Studio** [comment]
Having the same issue as in your third screenshot, but even worse. Have you managed to find a way to fix it?
![image](https://user-images.githubusercontent.com/43496707/122466387-8a3bb400-cfb9-11eb-91ba-2ee0423067c0.png)

**Comment by vatsaltanna** [comment]
Hello @Armoured-Door-Studio @jagritjkh, 

Could you please share a code snippet for this to reproduce this issue?

Thanks

**Comment by vatsaltanna** [comment]
Hello @Armoured-Door-Studio @jagritjkh,

Could you please share a code snippet for this to reproduce this issue?

Thanks

**Comment by vatsaltanna** [comment]
Hello Guys,

We recently have released a new version of the showcase view package `showcaseview: ^1.1.0`. please try the new version. Your problem should have been solved in the new release.

**Comment by vatsaltanna** [comment]
Feel free to reopen if it is still happening for you.
