### ISSUE TITLE
Showcase isn't rendering responsively

### ISSUE THREAD

**Issue by vbbandeira** [SimformSolutionsPvtLtd/flutter_showcaseview#86]
**Describe the bug**
When I minimize the Web Application that is displaying a long text using the Showcase, instead of having a line break responsively, the text goes beyond the screen that is being displayed and is not fully shown to the user, it is only displayed if you increase the screen size.

**To Reproduce**
1. Go to field 'description'
2. Write a very long text '...'
3. Debug the application with a small resolution 'minimize as much'

**Expected behavior**
I believe that there could be a line break in Showcase, so that everything is visible to the user without the need to maximize the size of the window.

**Screenshots**
In this, it's perfect!
![should_be-showcase](https://user-images.githubusercontent.com/25926739/102927625-14c1b180-4476-11eb-8f9d-a12f78d56b02.png)

But, when I minimize the Application:
![error_showcase](https://user-images.githubusercontent.com/25926739/102927633-17240b80-4476-11eb-9754-491d6a05e1e8.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. chrome]

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2 API 29]
 - OS: [e.g. Android 10]

**Comment by braysonjohn148** [comment]
any fix for thhis. have the same issue.

**Comment by bilaloz** [comment]
any fix for thhis. have the same issue.

**Comment by FatihAydin52** [comment]
I have that same problem.

**Comment by z85510** [comment]
Same
