### ISSUE TITLE
Cannot disable when user click outside showcase

### ISSUE THREAD

**Issue by satriantorobimo** [SimformSolutionsPvtLtd/flutter_showcaseview#87]
Hi, i want to disable when user click outside showcase. Because i have a logic when user click next on showcase widget(my custom). So when user click outside showcase, my logic not working and the showcase finished.

1. Showcase came out
2. I created next button to go to next showcase
3. When click outside showcase, it will to the next showcase. But my logic not working.

I expected i can disable user when click outside showcase, so it will be one access for go to next showcase with my button.

**Comment by deity256** [comment]
how do you make it go to next screen when hit next button

**Comment by nvshah** [comment]
@satriantorobimo, @deity256 

changes in a view to aforementioned requirement. (i.e #87) is attempted.
 
Please find below reference : 
[PR reference](https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/pull/115)

thanks

**Comment by vatsaltanna** [comment]
Hi @deity256 @satriantorobimo @nvshah , This feature is now available in latest version of `shwocaseview: 1.0.8`. You can use `disableBarrierInteraction: true` to achive your required behaviour.
