### ISSUE TITLE
ShowCase Widget Weird Sizing and Padding

### ISSUE THREAD

**Issue by datovarc** [SimformSolutionsPvtLtd/flutter_showcaseview#88]
**Describe the bug**

For some widgets, even though the text may be as simple as "a" the padding to the sides of the ShowCase is at least three times the size of the content (to each side)
For those widgets, if text is large enough it will completely be padded out of screen.

Please find attached a sample photo.

This widget has nothing special on it, it's a simple Card, rounded... Inside a Row. The ShowCase is in the Card.

This widget sits vertically in the middle of the screen and horizontally all the way to the right. The screenshot displays the full width of the screen in Portrait mode.

**Expected behavior**
Would expect the ShowCase Widget to behave with normal sizing/padding as with other widgets.

**Screenshots**
![IMG_20210203_001345](https://user-images.githubusercontent.com/33615845/106628388-b7606a80-65b4-11eb-8da3-51083e0b4ee1.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9
 - OS: Android 10 (MIUI 11... Xiaomi's OS)

**Comment by z85510** [comment]
Is there any solution for this bug ? I have large text and it doesn't show properly

**Comment by vatsaltanna** [comment]
Hello, @datovarc @z85510

We recently have released a new version of the showcase view package `showcaseview: ^1.1.0.` please try the new version. Your problem should have been solved in the new release.

**Comment by vatsaltanna** [comment]
Feel free to reopen if it is still happening for you.

**Comment by ch-muhammad-adil** [comment]
Here is the issue... How can I fix it?

<img width="336" alt="Screenshot 2021-11-22 at 9 22 44 PM" src="https://user-images.githubusercontent.com/8264639/142897568-d0ea6325-b5cb-495d-a178-6047d9eaa5bf.png">
