### ISSUE TITLE
ListView Item Support

### ISSUE THREAD

**Issue by ufukhawk** [SimformSolutionsPvtLtd/flutter_showcaseview#90]
How can I use it on any List's item? Does it support this?

I want to add a description for that item on the item of the list.
However, as far as I understand this is not supported.

**Comment by ufukhawk** [comment]
i solved.

     `istView.builder(
        shrinkWrap: true,
        itemBuilder: (cont, index) {
          return index == 0 ? ShowCase(key: accountItemShowCase,
                                       title: 'Başlık',
                                       description:'Açıklama', child:bankAccountItem(idx)) : bankAccountItem(index);
        },
        itemCount: items.length,
      )`

**Comment by shubhambsps** [comment]
This will work for only first item of the list. How to do it for all the items in the list?
