### ISSUE TITLE
ONTARGETCLICK NOT WORKING !!!!!

### ISSUE THREAD

**Issue by yanisG** [SimformSolutionsPvtLtd/flutter_showcaseview#91]
when i use onTargetClick nothing happens

**Comment by braysonjohn148** [comment]
Yeah!  for me it calls the function am calling but when it opens the second screen. It is still there

**Comment by lokeshpaladugula** [comment]
yeah.. its not working.. not even calling that function

**Comment by maksof-Hussain** [comment]
is there any solution found for it? in my case, disposeOnTap and onTargetClick Both are not working.

**Comment by CaptainDario** [comment]
I seem to encounter the same issue.
When I put 
```{dart}
...
disposeOnTap: true,
onTargetClick: () {
    print("test");
}
...
```
nothing happens. Am I doing something wrong?

**Comment by furbnmax** [comment]
I have the same issue. OnTargetClick is not calling the function. OnTooltipClick is working. 
Please fix!!!

Is there any option to disable clicking on any part of the screen but the target to continue?

**Comment by vatsaltanna** [comment]
@furbnmax I tried to reproduce this issue, but it was working fine for me could you please provide more information on the issue like the Code snippet of the widgte?

**Comment by vatsaltanna** [comment]
Hello Guys,

We recently have released a new version of the showcase view package `showcaseview: ^1.1.0`. please try the new version. Your problem should have been solved in the new release.

**Comment by vatsaltanna** [comment]
Feel free to reopen if it is still happening for you.
