### ISSUE TITLE
How to save showcase state

### ISSUE THREAD

**Issue by mado-bohsali** [SimformSolutionsPvtLtd/flutter_showcaseview#97]
**I am using 4 keys in 3 different pages**

I am using sharedPreferences to save showcase to true if the user clicked on ToolTip or Target
But once I terminate the app and load it again, the showcases still play...

Plus, I get sometimes GlobalKey has been used multiple times

**Comment by meetjanani** [comment]
@mado-bohsali  Could you please provide us your code snippet where you use showcase view along with your parent widget & condition of SharedPreference that you are using. where you facing such GlobalKey multiple times / showcase is playing every time on app launch. so we can investigate more on this.
Thanks

**Comment by mado-bohsali** [comment]
No need dear. I am no longer using Showcase widgets. Appreciate your follow up.
