### ISSUE TITLE
I request a skip button to stop showcasing the widgets.

### ISSUE THREAD

**Issue by giritlgc** [SimformSolutionsPvtLtd/flutter_showcaseview#99]
I am very happy using this package. I have one request for a feature. I want an option to skip the process of showcasing the widgets. 

For example, If I have five widgets to show, the process starts showing each widget in a sequence. Right now, I need to look at all widgets to complete the process.  I want to stop the process after looking first two widgets. 

Please add a feature that enables user to skip or stop the process in the middle of squence.

**Comment by mikeyyg96** [comment]
This would be useful

**Comment by GarryLaly** [comment]
You can make it self UI for Skip, with run method

```
ShowCaseWidget.of(context).dismiss();
```

**Comment by SalishKumar** [comment]
@AMuellerAtAHS, how did you show the skip button throughout the app tour?

**Comment by Anneress** [comment]
> @AMuellerAtAHS, how did you show the skip button throughout the app tour?

Can you explain your question a bit further?

**Comment by MehmetMcfly** [comment]
> @SalishKumar
> 
> > @AMuellerAtAHS, how did you show the skip button throughout the app tour?
> 
> I don't understand this question. Can you please explain it?

With the method of @AMuellerAtAHS the dismiss button/option will only be shown for the Showcase you are including it in.
It would make more sense to have one button somewhere on the screen that skips the showcase. 

I couldn't find a way to overlay the showcase with a button to do this. When I use a stack, the button seems to get blurred and stay "behind" the showcasewidget.

**Comment by vitulgoyani** [comment]
any update for the skip button?

**Comment by amatier2** [comment]
> any update for the skip button?

If you use `Showcase.withWidget()` you can pass in any widget to be the "dialog" that pops up. Inside there you can use a button with an `onPressed` set to `ShowCaseWidget.of(context)!.dismiss()` to skip, unless you are looking to just skip the current step then the logic gets a little fuzzy.

**Comment by AMuellerAtAHS** [comment]
There is a pull request waiting to get reviewed and merged: #156

**Comment by sharpsaravanan** [comment]
Please add the global skip button

**Comment by qpalzm963** [comment]
Please add the global skip button

**Comment by pawarn** [comment]
I need similar global skip button and NEXT button in showcaseview

**Comment by aditya-css** [comment]
One can certainly use `Showcase.withWidget` to create a custom skip button along with `ShowCaseWidget.of(context).dismiss()` function. If it is desired that such a button stays at a constant place and not attached to any particular `Showcase` then an issue (#395) with PR (#396) is already open and thus I am closing this one. Thanks for participating.
